### ISSUE TITLE
PHP版本要求

### ISSUE THREAD

**Issue by cshaptx4869** [walkor/webman#100]
官方文档上写着，webman数据库采用的是 illuminate/database。而安装 composer require illuminate/database ^8.0 需要PHP7.3及以上。所以默认webman的PHP版本要求是 ≥7.3 咯

**Comment by walkor** [comment]
webman没有强制使用某个数据库或者版本。可以使用 illuminate/database 8.0，也可以使用 illuminate/database 7.0，也可以使用其它数据库
