### ISSUE TITLE
在webman有没有什么好的方案可以给vue 构建好的dist目录提供http服务

### ISSUE THREAD

**Issue by dhw-daniel** [walkor/webman#101]

**Comment by walkor** [comment]
我对vue不熟悉，我的理解是直接把dist目录放到public下就能访问了

**Comment by xuellbcd** [comment]
我都是直接用nginx给dist指定一个单独的二级域名。如果作为二级目录，好多东西都需要配置，各种出问题。比如ueditor这种第三方插件，配置了好久没弄好，后来就干脆不搞二级目录了。
反正webman也最好是需要用nginx做一个代理。不如直接给vue的dist直接指定一个二级域名，比如admin.xxx.com

**Comment by Tinywan** [comment]
@xuellbcd nginx config

webman.tinywan.com.conf

```
server {
  listen 443 ssl;
  server_name webman.tinywan.com;

  ssl_certificate /home/ssl/chain.crt;
  ssl_certificate_key /home/ssl/key.key;

  location / {
    proxy_pass http://127.0.0.1:8787;
  }
}
```

**Comment by dhw-daniel** [comment]
感谢回复，我这边是知道可以通过nginx代理方式处理webman  项目和vue项目的，目前是想了解下，单纯只用webman做http服务时是否可以整合vue项目，整合后是否会出现路由寻址问题、缓存、稳定性等这些问题，是否可以上生产还是只能用来做测试环境这些信息

**Comment by xcorp1986** [comment]
@dhw-daniel 像vue这样的前后端分离项目，个人建议你分开两个域名进行部署，我目前是使用vercel这样的平台进行部署的，push代码自动触发build，自动cdn和https真的很好用，最关键的是完全免费！

**Comment by Tinywan** [comment]
请关闭issue
