### ISSUE TITLE
有个问题

### ISSUE THREAD

**Issue by Mitirrli** [walkor/webman#104]
使用php start.php start开启服务后 不关闭是一直可以正常使用的 但使用cmd + c 关闭服务 会一直提示下列warning, 是我哪里配置错误了吗

环境: docker
PHP版本: php:8.0.0-cli-alpine

`
Warning: EventBase::loop(): Failed to invoke event callback in /www/vendor/workerman/workerman/Events/Event.php on line 195
`

**Comment by walkor** [comment]
Fixed in workerman 4.0.18.
Please upgrade workerman.
`composer require workerman/workerman ^4.0.18`
