### ISSUE TITLE
请求OnMessage处理问题

### ISSUE THREAD

**Issue by weijer** [walkor/webman#108]
测试软件：Postman
问题：POST请求使用了 application/json JSON 请求参数，然后切换到GET请求，OnMessage会接收不到信息

不知道这个是不是一个BUG，正常GET参数肯定不会这样传递！

**Comment by walkor** [comment]
看下是不是Get请求带了包体，workerman不支持get请求带包体。

**Comment by weijer** [comment]
是的get请求带包体了，所以我问问是不是个bug
