### ISSUE TITLE
需要强路由支持

### ISSUE THREAD

**Issue by weijer** [walkor/webman#109]
昨天提交了一个PR：https://github.com/walkor/webman-framework/pull/5

如果大佬有更好方案麻烦支持下！

**Comment by walkor** [comment]
我不太理解你的强制路由是什么意思。
比如不设置任何路由的时候，访问 `/blog/view`，默认是访问 `app\controller\Blog` 类的 `view`方法。
开启强制路由后，就不允许默认访问了？

**Comment by weijer** [comment]
强路由就是开启之后，不会自动去匹配 module/controller/method 了，必须匹配配置的路由

**Comment by walkor** [comment]
```php
....其它路由.....

Route::any('/[{a}[/[{b}[/[{c}[/]]]]]]', function () {
    return response('<h1>404 Not Found</h1>', 404);
});
```
在路由配置里最后一行加上上面这个路由，就可以禁止自动匹配了。你可以把这个路由规则理解为一个禁止自动匹配app/controller/method的fallback。

**Comment by weijer** [comment]
> ```
> ....其它路由.....
> 
> Route::any('/[{a}[/[{b}[/[{c}[/]]]]]]', function () {
>     return response('<h1>404 Not Found</h1>', 404);
> });
> ```
> 
> 在路由配置里最后一行加上上面这个路由，就可以禁止自动匹配了。你可以把这个路由规则理解为一个禁止自动匹配app/controller/method的fallback。

这样也是个办法
