### ISSUE TITLE
搭配nginx时，webman放子目录，路由无效了

### ISSUE THREAD

**Issue by l12ab** [walkor/webman#110]
我用nginx来代理访问webman程序，配置了
```
location /webman/ {
    proxy_pass   http://php:8787;
}
```

但是，此时所有路由就无效了，路由必须每条记录加上/webman前缀，并且url留空时，也不能访问默认的index/index方法。

尝试过中间件，但是因为调用中间件时其实已经完成了路由，所以此方案不行。

尝试过修改框架Route.php的addRoute方法，添加了
```
$path = "/webman{$path}";
```
但是，仍然不能让url留空访问index/index方法

所以有没有一个方法能给路由添加一个base_uri前缀？

**Comment by walkor** [comment]
nginx配置里加一个重定向试下
```
location /webman/ {
    rewrite ^/webman(/.*)$ $1 break;
    proxy_pass   http://php:8787;
}
```

**Comment by l12ab** [comment]
可以了，感谢
