### ISSUE TITLE
Best way to use async http connection from controller?

### ISSUE THREAD

**Issue by latypoff** [walkor/webman#114]
I want to get rid of file_get_contents/curl from controllers code, which blocks entire process. How should I use async non-blocking http connection to remote host? Any recipes?

Just noticed, when I try to connect from any controller to myself, then it times out.

**Comment by walkor** [comment]
Webman handles requests in synchronous mode and does not support asynchronous mode.

**Comment by latypoff** [comment]
Sad. I'll try to use queues instead. Thanks.

**Comment by latypoff** [comment]
I finally get it worked even with blocked calls. I just set reusePort to false in config/server.php, everything is worked like a charm.
It seems automatic detection of SO_REUSEPORT feature is working not smart enough.
