### ISSUE TITLE
etcd服务发现和注册

### ISSUE THREAD

**Issue by weijer** [walkor/webman#115]
老大帮我看看这样方案是否可行，

1、通过写一个go etcd 注册和发现服务端，同时启动一个本地ws服务端
2、PHP通过workerman ws客户端去调用go接口

**Comment by walkor** [comment]
可行

**Comment by weijer** [comment]
通过webman的自定义进程我可以快速建立ws客户端去调用go服务进行服务注册和发现了，但是webman框架内怎么拿到这个信息了！

**Comment by walkor** [comment]
你是要每个webman进程都拿到这个信息？
你可以把这个信息写到磁盘，然后webman需要这个信息的时候去读下磁盘。

**Comment by weijer** [comment]
写到redis里面去了，ws客户端进程里面定时维护etcd redis 服务缓存。期待老大写个 ectd组件
