### ISSUE TITLE
Mysql error log everytime open the web

### ISSUE THREAD

**Issue by haidarvm** [walkor/webman#116]
` [Warning] Aborted connection 23366 to db: 'dbname' user: 'dbuser' host: 'localhost' (Got timeout reading communication packets)
`
How to get rid off it ?

**Comment by walkor** [comment]
I have never encountered such a mistake. I found some answers on the Internet, hoping to help you.

https://cn.bing.com/search?q=Aborted%20connection%20to%20db%20%20(Got%20timeout%20reading%20communication%20packets&qs=n&form=QBRE&sp=-1&pq=aborted%20connection%20to%20db%20(got%20timeout%20reading%20communication%20packets&sc=0-67&sk=&cvid=08FBA16180DC4A8D9C321D6C2534A5A2
https://dba.stackexchange.com/questions/282968/mariadb-aborted-connection-got-timeout-reading-communication-packets
https://dba.stackexchange.com/questions/205398/mysql-got-timeout-reading-communication-packets-when-reading-federated-table
