### ISSUE TITLE
关闭默认路由也同时无法读取public内的css js文件了

### ISSUE THREAD

**Issue by teckwei1993** [walkor/webman#119]
加上以下的代码后，原本可以访问的public内的文件也变成404了
`Route::any('/[{a}[/[{b}[/[{c}[/]]]]]]', function () {
    return response('<h1>404 Not Found</h1>', 404);
});`

文件链接：http://localhost:8787/css/app.css （public/css/app.css）

**Comment by teckwei1993** [comment]
另外一个问题是发现以下访问首页代码也不能共存
`Route::get('/', function ($request) {
    return response('test homepage');
});

Route::any('/[{a}[/[{b}[/[{c}[/]]]]]]', function () {
    return response('<h1>404 Not Found</h1>', 404);
});`

浏览是回应
This page isn’t working
localhost didn’t send any data.
ERR_EMPTY_RESPONSE

**Comment by walkor** [comment]
更新下 workerman/webman-framework 到 1.0.13 或者后续更高版本。
在config/route.php 里增加一行如下代码禁止默认路由。
```
Route::disableDefaultRoute();
```
