### ISSUE TITLE
关于assign的疑问

### ISSUE THREAD

**Issue by theEndc** [walkor/webman#121]
support/view/Raw::assign();
因为workerman是常驻进程,这样调用assign,static $_vars 在并发情况下是否会被污染?
$_vars带上session_id分组会不会好一点呢?

**Comment by walkor** [comment]
进程间变量是隔离的，所以进程间不会有问题。
单个进程内请求是顺序处理的，也不会有并发问题。
关于常驻内存，请求最后调用view()方法后会清理掉assign()的变量，所以在调用support/view/Raw::assign()后记得调用view()就不会有问题了。
