### ISSUE TITLE
after update webman using composer all route is now error

### ISSUE THREAD

**Issue by haidarvm** [walkor/webman#125]
```
Route set to /route-test is not callable
Route set to / is not callable
```
How to fix it ?

**Comment by walkor** [comment]
Open config/route.php and remove `Route::any('/', ...` and `Route::any('/route-test', ...` .

**Comment by haidarvm** [comment]
so how the correct syntax to use route ?

**Comment by walkor** [comment]
http://www.workerman.net/doc/webman#/route


Here is doc for route.&nbsp;

**Comment by haidarvm** [comment]
No, the problem is when we use Uppercase
`Route::any('/', 'app\controller\Home@index');`
it should be lowercase
`Route::any('/', 'app\controller\home@index');`
