### ISSUE TITLE
没有内置数据库连接池么?

### ISSUE THREAD

**Issue by zhangqian66** [walkor/webman#127]

**Comment by walkor** [comment]
webman单个进程内请求是排队处理的，单个进程内并不会有并发处理请求的情况，也就是单个进程内不会并发访问数据库，每个请求用完数据库连接后，下个请求可以直接复用数据库连接，所以webman框架内部用不到连接池。
虽然也可以做连接池，但是没有必要，而且数据库单例在webman里性能是最好的，压测看性能比一些协程+连接池的web框架还要高。
性能数据方面可以参考  https://www.techempower.com/benchmarks/#section=test&runid=646af5ea-0fae-448d-b77d-bc27b13d73e5&hw=ph&test=db&l=zg24n3-73&a=2

**Comment by zhangqian66** [comment]
我可以理解为是在网络io进程的上下文同步执行的业务代码对吧,如果有一个请求处理阻塞会影响整个进程维护的连接,所以最好还是用来做一些高性能的至少是不依赖数据库的业务?

**Comment by walkor** [comment]
> 我可以理解为是在网络io进程的上下文同步执行的业务代码对吧,如果有一个请求处理阻塞会影响整个进程维护的连接

是的。

> 所以最好还是用来做一些高性能的至少是不依赖数据库的业务?

也可以做依赖数据库的项目。如果有操作数据库多开一些进程就好了，比如cpu的2-4倍，进程遇到阻塞会自动切换，从而提高并发。php-fpm性能那么差，并且也是同步阻塞业务，也没影响它做依赖数据库的项目。大部分业务没有达到需要极致性能的地步，同步阻塞性能足够满足绝大部分业务，如果真是需要极致性能，也不会选择操作数据库了。

**Comment by a6965921** [comment]
webman单个进程内请求是排队处理的，单个进程内并不会有并发处理请求的情况  请求是排队处理是什么意思     第一个请求没结束 第二个请求就不会开始？？

**Comment by walkor** [comment]
对于单个进程来说是这样。
多个进程是并发处理的，总体来看是并发处理。

**Comment by ihipop** [comment]
> 对于单个进程来说是这样。 多个进程是并发处理的，总体来看是并发处理。
所以我可以理解为：
假设最大进程数量为 N,
一旦有比较慢的业务（不限于数据库，任何的IO业务），比如一个业务需要1秒才能完成，
那么最大QPS处理能力就是 N/秒 了？

**Comment by walkor** [comment]
对
