### ISSUE TITLE
webman  自身是否有什么方案可以像nginx得到pv、uv、url、并发等类似的汇总结果

### ISSUE THREAD

**Issue by dhw-daniel** [walkor/webman#130]

**Comment by walkor** [comment]
nginx可以得到 pv、uv、url、并发等类似的汇总结果的方案是？

**Comment by dhw-daniel** [comment]
类似这种 命令  awk '{print $6}' host.access.log | wc -l
分析 access.log请求日志

**Comment by walkor** [comment]
你可以写个中间件来记录nginx这样类似的日志。
文档 https://www.workerman.net/doc/webman#/middleware
