### ISSUE TITLE
利用webman/redis-queue队列

### ISSUE THREAD

**Issue by weijer** [walkor/webman#131]
1、里面直接调用service 数据库连接怎么保持心跳了？
2、service里面用了request() 调用request数据，现在不经过request进行队列消费，这块有啥好的想法兼容下！

**Comment by walkor** [comment]
1、在`config/bootstrap.php` 里加入入下配置
```php
return [
    // .....省略其它配置....

    support\bootstrap\db\Heartbeat::class,
];
```
进程启动的时候会调用`support\bootstrap\db\Heartbeat.php`里的start方法，里面是个定时器，定时`select 1`，维持数据库连接。

2、这块不好兼容，一个是请求环境。一个是消费环境。

**Comment by weijer** [comment]
哦哦看到了心跳在process worker进程里面也会启动
