### ISSUE TITLE
数据库建议

### ISSUE THREAD

**Issue by zoujingli** [walkor/webman#14]
很多应用中只会用到一种或几种，能不能把数据库支持的驱动做成外挂库。
需要用的的时候 composer require 安装进去

**Comment by walkor** [comment]
比如说哪些驱动做成外挂库？

**Comment by zoujingli** [comment]
常用数据库一般是 mysql
其他的都可以做成 外挂库

**Comment by walkor** [comment]
webman 使用的是 illuminate/database，只加载这个一个库就行了，数据库除了illuminate/database没有其它库的依赖

**Comment by bestlake** [comment]
能不能出个 think-orm接入的指南

**Comment by walkor** [comment]
可以

**Comment by zoujingli** [comment]
现在是 database + redis，database 包含 340 个文件，一个包也能接受的。
redis, mongolog 可以分离出去不？

**Comment by walkor** [comment]
框架自身有记录日志，需要monolog。 redis 如果你不需要，可以从从composer.json中移除。

**Comment by zoujingli** [comment]
好的，现在纯框架文件数差不多达到了 2000 左右，感觉有些多

**Comment by walkor** [comment]
如果要移除redis，记得把 `config/bootstrap.php` 里的 `support\bootstrap\Redis::class` 删除。

**Comment by zoujingli** [comment]
明白，感谢回复！

**Comment by walkor** [comment]
@bestlake 
文档里增加了使用think-orm的说明，
地址：https://www.workerman.net/doc/webman#/db/others （如果看不到强制刷新下）
