### ISSUE TITLE
如何确保脚本不会被重复执行

### ISSUE THREAD

**Issue by Mitirrli** [walkor/webman#140]
项目使用负载均衡，如何实现不重复执行脚本。是在业务中自行加锁吗

**Comment by walkor** [comment]
不清楚你说的是什么脚本。如果不想重复执行，可以只在一台服务器上执行。或者业务代码里做排重，排重方案根据业务类型而定，没有统一方案，业务排重网上有很多文章可以参考。

**Comment by Mitirrli** [comment]
好的 谢谢了
