### ISSUE TITLE
redis连接不上

### ISSUE THREAD

**Issue by RyanKIrs** [walkor/webman#141]
大佬，新年好，我用phpstorm的工具远程连接redis可以连接上，但是webman连接不上，提示Error: Call to a member function connection() on null in /Users/ryan/Desktop/api/roast/support/bootstrap/Redis.php:235

**Comment by walkor** [comment]
config/bootstrap.php 里有一个 `support\bootstrap\Redis::class,` 配置看下是不是没加。

**Comment by RyanKIrs** [comment]
> config/bootstrap.php 里有一个 `support\bootstrap\Redis::class,` 配置看下是不是没加。

大佬，确认是加过的

**Comment by walkor** [comment]
我这没有你的环境，无法定位。有可能你改动了哪里的源码(比如 start.php)，导致support/bootstrap/Redis::start 方法没执行。

**Comment by RyanKIrs** [comment]
> 我这没有你的环境，无法定位。有可能你改动了哪里的源码(比如 start.php)，导致support/bootstrap/Redis::start 方法没执行。

大佬，我重新安装试了，还是不行，mac11.2.1，php7.3，使用php -m | grep redis已经安装redis扩展，扩展版本Redis Version => 5.3.2，bootstrap已经添加，想问大佬是不是我服务器那边redis配置问题

**Comment by walkor** [comment]
按照手册示例来一遍吧 https://www.workerman.net/doc/webman#/redis
注意手册里有安装 `composer require illuminate/redis ^8.2.0`

如果还有问题，包括安装过程截图、配置截图、示例截图、测试方法截图、测试结果截图

**Comment by RyanKIrs** [comment]
大佬,重新安装后可以了
