### ISSUE TITLE
比swoole还快码

### ISSUE THREAD

**Issue by a6965921** [walkor/webman#143]
比swoole还快码

**Comment by walkor** [comment]
看具体业务场景。
helloworld webman比swoole快很多。
具体业务还要看具体情况。
不过从各大权威网站压测结果，不管是helloworld还是带数据库业务的，webman都比swoole以及基于swoole的协程框架都要快一些。
参见：
https://github.com/the-benchmarker/web-frameworks
https://www.techempower.com/benchmarks/#section=data-r20&hw=ph&test=plaintext&l=zik073-sf
