### ISSUE TITLE
cookie怎么使用呢

### ISSUE THREAD

**Issue by bestlake** [walkor/webman#15]
cookie设置不生效，求正确姿势

**Comment by walkor** [comment]
参考手册
https://www.workerman.net/doc/webman#/response?id=%e8%ae%be%e7%bd%aecookie
https://www.workerman.net/doc/webman#/request?id=%e8%8e%b7%e5%8f%96cookie

**Comment by bestlake** [comment]
看了手册，但如果我设置了cookie后，还有业务逻辑需要处理后才response呢？按手册上的用法就不行了。我看3.5会先往HttpCache写，最后reponse的时候再统一处理set-cookie。

**Comment by walkor** [comment]
控制器最终返回的是一个response对象就行。
```php
public function index(Request $request)
{
        // 创建一个对象
        $response = response();
        $response->cookie('foo', 'value');

        // .... 业务逻辑省略

        // 设置要返回的数据
        $response->withBody('返回的数据');
        return $response;
}
```
