### ISSUE TITLE
redis 连接不用连接池真的好吗

### ISSUE THREAD

**Issue by a6965921** [walkor/webman#154]
redis 连接不用连接池真的好吗
我看下代码就用了单例      。。。如果高并发。。不是只能1个个处理数据了

**Comment by teg1c** [comment]
照你这么说,`fpm` 下岂不是更不能用了?

**Comment by walkor** [comment]
1、webman是同步模式，用不到连接池。
2、另外redis单例连接每秒可以处理数万redis请求，redis平均每个请求处理耗时小于1毫秒。
3、redis单例在webman下是最优方案，没有之一。
4、虽然没有连接池，但是压测性能比其它带连接池+协程的所有框架QPS都要高。不信可以自己压测下。

发两个权威压测数据，你自己可以感受下。
https://www.techempower.com/benchmarks/#section=data-r20&hw=ph&test=db&l=zik073-sf
https://github.com/the-benchmarker/web-frameworks

**Comment by a6965921** [comment]
> 照你这么说,`fpm` 下岂不是更不能用了?

fpm是短连接 每次请求创建个链接           webman是启动是的是创建的链接  2个不一样

**Comment by teg1c** [comment]
> > 照你这么说,`fpm` 下岂不是更不能用了?
> 
> fpm是短连接 每次请求创建个链接 webman是启动是的是创建的链接 2个不一样

你说的个啥?

**Comment by a6965921** [comment]
> > > 照你这么说,`fpm` 下岂不是更不能用了?
> > 
> > 
> > fpm是短连接 每次请求创建个链接 webman是启动是的是创建的链接 2个不一样
> 
> 你说的个啥?

不好意思我看错了
