### ISSUE TITLE
求助： 使用laravel的DB类的 dd方法或者 dump方法进行调试的时候报错了

### ISSUE THREAD

**Issue by Mylovecomes2me** [walkor/webman#163]
Call to undefined function Illuminate\\Database\\Query\\dd() ；
Error: Call to undefined function Illuminate\\Database\\Query\\dd() in /home/wwwroot/webman-master/vendor/illuminate/database/Query/Builder.php:3222\nStack trace:\n#0 /home/wwwroot/webman-master/app/admin/controller/User.php(158): Illuminate\\Database\\Query\\Builder->dd()\n#1 /home/wwwroot/webman-master/vendor/workerman/webman-framework/src/App.php(234): app\\admin\\controller\\User->appInfo()\n#2 /home/wwwroot/webman-master/app/middleware/ActionHook.php(24): Webman\\App::Webman\\{closure}()\n#3 /home/wwwroot/webman-master/vendor/workerman/webman-framework/src/App.php(228): app\\middleware\\ActionHook->process()\n#4 /home/wwwroot/webman-master/support/middleware/AccessControlTest.php(39): Webman\\App::Webman\\{closure}()\n#5 /home/wwwroot/webman-master/vendor/workerman/webman-framework/src/App.php(228): support\\middleware\\AccessControlTest->process()\n#6 /home/wwwroot/webman-master/vendor/workerman/webman-framework/src/App.php(313): Webman\\App::Webman\\{closure}()\n#7 /home/wwwroot/webman-master/vendor/workerman/webman-framework/src/App.php(150): Webman\\App::findRoute()\n#8 /home/wwwroot/webman-master/vendor/workerman/workerman/Connection/TcpConnection.php(637): Webman\\App->onMessage()\n#9 /home/wwwroot/webman-master/vendor/workerman/workerman/Events/Select.php(293): Workerman\\Connection\\TcpConnection->baseRead()\n#10 /home/wwwroot/webman-master/vendor/workerman/workerman/Worker.php(2430): Workerman\\Events\\Select->loop()\n#11 /home/wwwroot/webman-master/vendor/workerman/workerman/Worker.php(1555): Workerman\\Worker->run()\n#12 /home/wwwroot/webman-master/vendor/workerman/workerman/Worker.php(1385): Workerman\\Worker::forkOneWorkerForLinux()\n#13 /home/wwwroot/webman-master/vendor/workerman/workerman/Worker.php(1359): Workerman\\Worker::forkWorkersForLinux()\n#14 /home/wwwroot/webman-master/vendor/workerman/workerman/Worker.php(1692): Workerman\\Worker::forkWorkers()\n#15 /home/wwwroot/webman-master/vendor/workerman/workerman/Worker.php(1641): Workerman\\Worker::monitorWorkersForLinux()\n#16 /home/wwwroot/webman-master/vendor/workerman/workerman/Worker.php(544): Workerman\\Worker::monitorWorkers()\n#17 /home/wwwroot/webman-master/start.php(156): Workerman\\Worker::runAll()\n#18 {main}"

**Comment by Mylovecomes2me** [comment]
"msg": "Class 'Symfony\\Component\\VarDumper\\VarDumper' not found",
    "traces": "Error: Class 'Symfony\\Component\\VarDumper\\VarDumper' not found in /home/wwwroot/webman-master/vendor/illuminate/collections/Traits/EnumeratesValues.php:219\nStack trace:\n#0 /home/wwwroot/webman-master/vendor/illuminate/collections/Traits/EnumeratesValues.php(234): Illuminate\\Support\\Collection->Illuminate\\Support\\Traits\\{closure}()\n#1 /home/wwwroot/webman-master/vendor/illuminate/collections/Traits/EnumeratesValues.php(220): Illuminate\\Support\\Collection->each()\n#2 /home/wwwroot/webman-master/vendor/illuminate/collections/Traits/EnumeratesValues.php(204): Illuminate\\Support\\Collection->dump()\n#3 /home/wwwroot/webman-master/app/admin/controller/User.php(159): Illuminate\\Support\\Collection->dd()\n#4 /home/wwwroot/webman-master/vendor/workerman/webman-framework/src/App.php(234): app\\admin\\controller\\User->appInfo()\n#5 /home/wwwroot/webman-master/app/middleware/ActionHook.php(24): Webman\\App::Webman\\{closure}()\n#6 /home/wwwroot/webman-master/vendor/workerman/webman-framework/src/App.php(228): app\\middleware\\ActionHook->process()\n#7 /home/wwwroot/webman-master/support/middleware/AccessControlTest.php(39): Webman\\App::Webman\\{closure}()\n#8 /home/wwwroot/webman-master/vendor/workerman/webman-framework/src/App.php(228): support\\middleware\\AccessControlTest->process()\n#9 /home/wwwroot/webman-master/vendor/workerman/webman-framework/src/App.php(313): Webman\\App::Webman\\{closure}()\n#10 /home/wwwroot/webman-master/vendor/workerman/webman-framework/src/App.php(150): Webman\\App::findRoute()\n#11 /home/wwwroot/webman-master/vendor/workerman/workerman/Connection/TcpConnection.php(637): Webman\\App->onMessage()\n#12 /home/wwwroot/webman-master/vendor/workerman/workerman/Events/Select.php(293): Workerman\\Connection\\TcpConnection->baseRead()\n#13 /home/wwwroot/webman-master/vendor/workerman/workerman/Worker.php(2430): Workerman\\Events\\Select->loop()\n#14 /home/wwwroot/webman-master/vendor/workerman/workerman/Worker.php(1555): Workerman\\Worker->run()\n#15 /home/wwwroot/webman-master/vendor/workerman/workerman/Worker.php(1385): Workerman\\Worker::forkOneWorkerForLinux()\n#16 /home/wwwroot/webman-master/vendor/workerman/workerman/Worker.php(1359): Workerman\\Worker::forkWorkersForLinux()\n#17 /home/wwwroot/webman-master/vendor/workerman/workerman/Worker.php(1692): Workerman\\Worker::forkWorkers()\n#18 /home/wwwroot/webman-master/vendor/workerman/workerman/Worker.php(1641): Workerman\\Worker::monitorWorkersForLinux()\n#19 /home/wwwroot/webman-master/vendor/workerman/workerman/Worker.php(544): Workerman\\Worker::monitorWorkers()\n#20 /home/wwwroot/webman-master/start.php(156): Workerman\\Worker::runAll()\n#21 {main}"

**Comment by walkor** [comment]
运行 `composer require symfony/var-dumper` 试下

**Comment by Mylovecomes2me** [comment]
安装过这个包

**Comment by Mylovecomes2me** [comment]
![Uploading image.png…]()

**Comment by Mylovecomes2me** [comment]
[root@iZuf60ajic0vbvjg11qql9Z webman-master]# composer require symfony/var-dumper
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Warning from https://mirrors.aliyun.com/composer: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2
Using version ^5.2 for symfony/var-dumper
./composer.json has been updated
Loading composer repositories with package information
Warning from https://mirrors.aliyun.com/composer: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
> @php -r "file_exists('.env') || copy('.env.example', '.env');"
22 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

**Comment by Mylovecomes2me** [comment]
建议大佬组织一个交流群 ，webman 缺少一个大家交流互助的平台
