### ISSUE TITLE
请教一下数据库使用Thinkorm的问题

### ISSUE THREAD

**Issue by amibk** [walkor/webman#168]
现在在正式项目中使用了webman，主要用于API接口，但是正式上线一段时间后，数据出现异常，查看日志发现经常出现Error while sending STMT_CLOSE packet，检查了逻辑代码，没有错误的SQL语句，是对Thinkorm支持不友好吗？

**Comment by walkor** [comment]
发下完整抱错，包括文件和调用栈

**Comment by amibk** [comment]
关于具体出错追踪信息：
`Fatal error: Uncaught ErrorException: Error while sending STMT_CLOSE packet. PID=4259 in /www/wwwroot/xxx.xxx.com/vendor/topthink/think-orm/src/db/PDOConnection.php:602
Stack trace:
#0 /www/wwwroot/xxx.xxx.com/vendor/topthink/think-orm/src/db/PDOConnection.php(602): {closure}(2, 'Error while sen...', '/www/wwwroot/op...', 602, Array)
#1 /www/wwwroot/xxx.xxx.com/vendor/topthink/think-orm/src/db/PDOConnection.php(1575): think\db\PDOConnection->free()
#2 /www/wwwroot/xxx.xxx.com/vendor/topthink/think-orm/src/db/Connection.php(345): think\db\PDOConnection->close()
#3 [internal function]: think\db\Connection->__destruct()
#4 {main}
  thrown in /www/wwwroot/xxx.xxx.com/vendor/topthink/think-orm/src/db/PDOConnection.php on line 602

Fatal error: Uncaught ErrorException: Error while sending STMT_CLOSE packet. PID=4260 in /www/wwwroot/xxx.xxx.com/vendor/topthink/think-orm/src/db/PDOConnection.php:602
Stack trace:
#0 /www/wwwroot/xxx.xxx.com/vendor/topthink/think-orm/src/db/PDOConnection.php(602): {closure}(2, 'Error while sen...', '/www/wwwroot/op...', 602, Array)
#1 /www/wwwroot/xxx.xxx.com/vendor/topthink/think-orm/src/db/PDOConnection.php(1575): think\db\PDOConnection->free()
#2 /www/wwwroot/xxx.xxx.com/vendor/topthink/think-orm/src/db/Connection.php(345): think\db\PDOConnection->close()
#3 [internal function]: think\db\Connection->__destruct()
#4 {main}
  thrown in /www/wwwroot/xxx.xxx.com/vendor/topthink/think-orm/src/db/PDOConnection.php on line 602
.........
`
文件调用thinkorm片段，基本都是查询或增加。
``/**
     * 获取渠道列表
     * @param Request $request
     * @return \support\Response
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\DbException
     * @throws \think\db\exception\ModelNotFoundException
     */
    public function channelList(Request $request): Response
    {
        $page = $request->input('page','1');
        $limit = $request->input('limit','20');
        $agent_id = $request->input('agent_id');
        $list = Db::table('table_name')
            ->field('desc,id,creat_time,channel_name')
            ->where(['uid'  => $agent_id])
            ->page($page,$limit)
            ->select();
        if (!empty($list)){
            $this->data['code'] = 'SUCCESS';
            $this->data['data'] = $list;
        }else{
            $this->data['code'] = 'FAIL';
            $this->data['msg'] = '暂无更多数据';
        }
        return resMsg($this->data); // 封装类似自带的json方法
    }`

**Comment by amibk** [comment]
好像是thinkorm不支持cli模式嘛，每隔一段时间就会报错，重新启动一下webman又恢复，再隔一段时间又报错。

**Comment by walkor** [comment]
应该是mysql连接长时间无操作被mysql服务端断开了。
thinkorm有个自动重连选项 break_reconnect ，在配置里加上 `break_reconnect=>true` 试下。

如果还不行，就加一个定时器定时`select 1`保持连接活跃，避免断开。
参考 support/bootstrap/db/Heartbeat.php

**Comment by amibk** [comment]
您好，最初配置thinkorm时，就加了break_reconnect 参数且赋值true，我现在尝试一下您说的mysql心跳

**Comment by amibk** [comment]
你好，一夜过去，查看运行状态，workerman有退出次数，但是没有退出状态，如何追踪错误？
![webman](https://user-images.githubusercontent.com/26061368/111729426-02ef7f00-88aa-11eb-98c1-a455b7223ee8.png)

**Comment by walkor** [comment]
退出码为0，说明没有错误，可能是你们运行了reload，进程正常重启。
