### ISSUE TITLE
想问问在webman里可以用 sleep(10) 吗?

### ISSUE THREAD

**Issue by teckwei1993** [walkor/webman#169]
如题

workerman 文档中: 不要使用exit die sleep语句
webman 文档中: 不要执行exit die语句

所以好奇能否在 webman 用 sleep 呢?

**Comment by walkor** [comment]
不能

**Comment by teckwei1993** [comment]
如果我要在controller里写类似等待30秒内redis的key有value就立即返回, 我该如何处理?

**Comment by walkor** [comment]
想办法优化下业务逻辑。或者前端用ajax每秒检查一次。

**Comment by walkor** [comment]
人少不影响。

**Comment by teckwei1993** [comment]
可是我这人多怎么办？每人请求次数又不多

**Comment by walkor** [comment]
人多用websocket
