### ISSUE TITLE
mysql 操作错误直接抛出异常？？不是返回值吗

### ISSUE THREAD

**Issue by a6965921** [walkor/webman#170]
mysql 操作错误直接抛出异常？？不是返回值吗        没返回 不好操作呀 写tcc分布式事务蛋疼了

**Comment by walkor** [comment]
webman本身不提供数据库，数据库可以用laravel或者tp或者其它的数据库组件。
至于这些数据库组件是否抛出异常，webman无法控制。

不过总体来说抛出异常更方便些，这样不用每个数据调用都判断是否成功。

**Comment by a6965921** [comment]
我要获取失败状态   然后写逻辑。。。数据库组件提不了issue

**Comment by a6965921** [comment]
他这种我都不知道 怎么高了

**Comment by a6965921** [comment]
知道了直接try
