### ISSUE TITLE
session无法获取，打印

### ISSUE THREAD

**Issue by RyanKIrs** [walkor/webman#171]
![Uploading image.png…]()

无法获取带session数据，但是在login里面是可以获取到的，请教下大佬是什么原因

**Comment by walkor** [comment]
什么叫无法获取带session的数据？截图没上传成功，看不到截图。

**Comment by RyanKIrs** [comment]
> 什么叫无法获取带session的数据？截图没上传成功，看不到截图。
我在获取验证码函数中里面使用$request->session()->set('captcha')保存到session成功，但是在index方法中使用$request->session()->get('captcha')为NULL，都是在同一个login控制器下

**Comment by walkor** [comment]
session数据会在session对象析构的时候自动保存。可能你在哪里保存了session对象，session对象没销毁导致session没有保存。
调用`$request->session()->set('captcha')` 后调用 `$request->session()->save()`试下。
