### ISSUE TITLE
request对象添加自定义数据

### ISSUE THREAD

**Issue by RyanKIrs** [walkor/webman#172]
大佬，请求下，中间件解析token后将里面自定义数据添加到request对象中，在控制器里面获取，类似laravel的$request-.merge()方法

**Comment by walkor** [comment]
php里对象是可以动态添加属性的，在中间件里给$request对象添加属性，在控制器里直接获取就行。
比如在中间件里添加属性data
```php
$request->data = 'some value';
```
控制器里直接读取属性的值即可
```php
var_dump($request->data);
```

**Comment by RyanKIrs** [comment]
> php里对象是可以动态添加属性的，在中间件里给$request对象添加属性，在控制器里直接获取就行。
> 比如在中间件里添加属性data
> 
> ```
> $request->data = 'some value';
> ```
> 
> 控制器里直接读取属性的值即可
> 
> ```
> var_dump($request->data);
> ```

好的，谢谢大佬，已经解决了
