### ISSUE TITLE
有没有办法webman出现故障了 让他请求laravel框架

### ISSUE THREAD

**Issue by a6965921** [walkor/webman#179]
有没有办法webman出现故障了 让他请求laravel框架 
webman不让人放心。。。我要走二手准备

**Comment by teg1c** [comment]
既然不放心就不要上线,等测试没问题再上线

**Comment by a6965921** [comment]
> 既然不放心就不要上线,等测试没问题再上线

我怕中途挂了   有什么办法检测吗

**Comment by teg1c** [comment]
> > 既然不放心就不要上线,等测试没问题再上线
> 
> 我怕中途挂了 有什么办法检测吗 我就想到写个自动化脚本 请求webman 运行1个月看看有没有挂 不知道你有没有其他方法

你可以写一个 shell 脚本监控这个进程是否异常

**Comment by walkor** [comment]
webman 已经很多人用在正式环境了，webman自身很稳定没有问题。不放心的话可以自己写监控脚本。
