### ISSUE TITLE
有没有推荐使用的缓存组件？

### ISSUE THREAD

**Issue by anlla** [walkor/webman#181]
有没有推荐使用的缓存组件？

**Comment by walkor** [comment]
https://github.com/doctrine/cache
https://github.com/symfony/cache
都可

**Comment by anhao** [comment]
框架考虑直接集成一个缓存组件吗

**Comment by douno23** [comment]
> https://github.com/doctrine/cache https://github.com/symfony/cache 都可

mark一下，最近在找文件缓存的插件，Google搜索了几个都用不了，只好自己写了一个。 找时间试试这个。
另外说一句，第一个已经停止维护了哈
