### ISSUE TITLE
依赖注入问题

### ISSUE THREAD

**Issue by Tylorwill** [walkor/webman#184]
按照官方示例,使用接口实现依赖注入方式,一直提示报错,请教下大佬是怎么回事,其他方式都是好的
![image](https://user-images.githubusercontent.com/48007465/116204075-f72b8e00-a76e-11eb-8bba-8465d50c7a58.png)

**Comment by huhaophp** [comment]
![image](https://user-images.githubusercontent.com/15937325/116249386-5903ec00-a79f-11eb-9c4f-01245fa50200.png)
l路径看下

**Comment by RyanKIrs** [comment]
> ![image](https://user-images.githubusercontent.com/15937325/116249386-5903ec00-a79f-11eb-9c4f-01245fa50200.png)
> l路径看下
路径是对的，如果使用其它自定义注入就是可以的

**Comment by huhaophp** [comment]
![image](https://user-images.githubusercontent.com/15937325/116518639-15c28e00-a903-11eb-8f6d-4b0ce90caef9.png)
@RyanKIrs

**Comment by RyanKIrs** [comment]
> ![image](https://user-images.githubusercontent.com/15937325/116518639-15c28e00-a903-11eb-8f6d-4b0ce90caef9.png)
> @RyanKIrs

安装官网一样的，还是提示这个错误

**Comment by edenleung** [comment]
我尝试注入 `\webman\App` 也是不行

```php

<?php
namespace app\admin\controller;

use Webman\App;
use DI\Annotation\Inject;

class Auth
{
    /**
     * @Inject
     * @var App
     */
    protected $app;
    
    public function login()
    {
    }
}



```

@walkor

**Comment by walkor** [comment]
对，Webman\App 无法注入，因为无法确定App构造函数参数
