### ISSUE TITLE
publish this project to packagist.org 

### ISSUE THREAD

**Issue by fatrbaby** [walkor/webman#186]
目前安装本项目使用`git clone` 方式存在的一些问题：
 1  用户要先删除本项目的`.git`，才能初始化项目，将项目托管到自己的服务器
 2  用户很难选择版本

发布到 `packagist.org`的好处:
 1 本项目composer的type是`project`，发布上去后，醒目就能用`composer create-project walkor/webman`安装项目，不用自己删除.git了
 2 项目可以很简单的选择版本，如果以后本项目只支持php8了，那用户也可以选择php7的版本使用。

**Comment by walkor** [comment]
已经发布
composer create-project workerman/webman
