### ISSUE TITLE
blade 模板 兼容问题

### ISSUE THREAD

**Issue by icellus** [walkor/webman#195]
`vendor\workerman\webman-framework\src\Exception\ExceptionHandler.php`

>75        if (\method_exists($exception, 'render')) {
>76               return $exception->render();
>77        }

如果传入blade view 文件的 变量未定义 时，会抛出 `Illuminate\View\ViewException`  异常, 但是这个异常需要的参数 未正常传入，且 返回值 和 `ExceptionHandler` 期望的是不同的。

是否考虑注释这几行代码？

**Comment by walkor** [comment]
最终异常和调用栈是什么？

**Comment by icellus** [comment]
> 最终异常和调用栈是什么？

当 试图 在 `view` 中调用未定义变量的时候 

>ArgumentCountError: Too few arguments to function Illuminate\View\ViewException::render(), 
0 passed in /var/www/vendor/workerman/webman-framework/src/Exception/ExceptionHandler.php on line 76 and exactly 1 expected in /var/www/vendor/illuminate/view/ViewException.php:33 
Stack trace: 
#0 /var/www/vendor/workerman/webman-framework/src/Exception/ExceptionHandler.php(76): Illuminate\View\ViewException->render() 
#1 /var/www/support/exception/Handler.php(38): Webman\Exception\ExceptionHandler->render(Object(support\Request), Object(Illuminate\View\ViewException)) 
#2 /var/www/vendor/workerman/webman-framework/src/App.php(205): support\exception\Handler->render(Object(support\Request), Object(Illuminate\View\ViewException)) 
#3 /var/www/vendor/workerman/webman-framework/src/App.php(181): Webman\App::exceptionResponse(Object(Illuminate\View\ViewException), Object(support\Request)) 
#4 /var/www/vendor/workerman/workerman/Connection/TcpConnection.php(637): Webman\App->onMessage(Object(Workerman\Connection\TcpConnection), Object(support\Request)) 
#5 /var/www/vendor/workerman/workerman/Events/Select.php(293): Workerman\Connection\TcpConnection->baseRead(Resource id #228) 
#6 /var/www/vendor/workerman/workerman/Worker.php(2430): Workerman\Events\Select->loop() 
#7 /var/www/vendor/workerman/workerman/Worker.php(1554): Workerman\Worker->run() 
#8 /var/www/vendor/workerman/workerman/Worker.php(1384): Workerman\Worker::forkOneWorkerForLinux(Object(Workerman\Worker)) 
#9 /var/www/vendor/workerman/workerman/Worker.php(1358): Workerman\Worker::forkWorkersForLinux() 
#10 /var/www/vendor/workerman/workerman/Worker.php(1691): Workerman\Worker::forkWorkers() 
#11 /var/www/vendor/workerman/workerman/Worker.php(1640): Workerman\Worker::monitorWorkersForLinux() 
#12 /var/www/vendor/workerman/workerman/Worker.php(544): Workerman\Worker::monitorWorkers() 
#13 /var/www/start.php(156): Workerman\Worker::runAll() #14 {main}

**Comment by walkor** [comment]
已经去掉了
