### ISSUE TITLE
webman 的 request 怎么转换成符合PSR-7 规范， 或者直接实现PSR-7 

### ISSUE THREAD

**Issue by askuiop** [walkor/webman#196]
webman 的 request 怎么转换成符合PSR-7 规范， 或者直接实现PSR-7 ， 

不然的话，很多库都没法使用。

**Comment by askuiop** [comment]
例如， thephpleague/oauth2-server 这个库就需要请求和响应实现PSR-7 接口。 

建议webman 能兼容thephpleague/oauth2-server 这类库， 这样webman 在实现api 上会更加方便，优秀！

**Comment by walkor** [comment]
在需要PSR-7对象的时候自己创建下就好了。

比如使用workerman的psr7

`composer require workerman/psr7 ~1.4.4`

例如需要创建要给符合psr7的ServerRequest和Reponse时，这样创建
```php
$server_request = new Workerman\Psr7\ServerRequest((string)$request);// (string)$request 是将webman的request对象序列化字符串
$response = new Workerman\Psr7\Response(200, [], 'hello world');
```

**Comment by askuiop** [comment]
@walkor 我通过 $server_request = new Workerman\Psr7\ServerRequest((string)$request); 转化， 通过 post 方式提交的数据， 转化后 $server_request->getParsedBody() 获取的数据是空的？
