### ISSUE TITLE
同步curl 进程就容易busy 怎么解决？

### ISSUE THREAD

**Issue by weijer** [walkor/webman#199]
用 异步 http 怎么解决 Response

**Comment by walkor** [comment]
webman 不支持异步response。
busy说明进程在处理业务，并不一定是出现问题。

**Comment by weijer** [comment]
一旦有busy进程就会后面请求直接pending了

**Comment by walkor** [comment]
webman这里如果curl慢，除了多开进程，设置好curl超时时间，也没有好的办法。
