### ISSUE TITLE
webman 多文件上传问题，同名多文件无法获取，只能得到一个文件！

### ISSUE THREAD

**Issue by askuiop** [walkor/webman#202]
webman 处理多文件上传时：

postman 设置同名多文件上传， 例如表单名files

$request->file('files'), 只能获取到一个文件！

$request->file() 也只能获取到一个文件信息！

**Comment by walkor** [comment]
更新下主干的 workerman 和 webman-framework 

同名多文件上传客户端用法类似：
```html
<form method="post" action="http://127.0.0.1:8787/index/files" enctype="multipart/form-data" />
<input name="upload[]" multiple="multiple" type="file">
<input name="upload[]" multiple="multiple" type="file">
<input name="upload[]" multiple="multiple" type="file">
<input type="submit">
</form>
```

服务端用法类似:
```php
<?php
namespace app\controller;

class Index
{
    public function files(Request $request)
    {
        $files = $request->file('upload');
        if ($files) {
            foreach ($files as $file) {
                if ($file && $file->isValid()) {
                    $file->move(public_path() . '/files/myfile.' . $file->getUploadName());
                }
            }
            return json(['code' => 0, 'msg' => 'upload success']);
        }
        return json(['code' => 1, 'msg' => 'file not found']);
    }
}
```

**Comment by askuiop** [comment]
@walkor 我更新最新的代码， 但是是不行的， 我使用的是 postman 创建请求， 同名多文件上传还是只能获取到一个（最后一个）文件。 （当然不同名多文件是都能获取到的）
问题还是存在。

**Comment by walkor** [comment]
用html表单试下
```html
<form method="post" action="http://127.0.0.1:8787/index/files" enctype="multipart/form-data" />
<input name="upload[]" multiple="multiple" type="file">
<input name="upload[]" multiple="multiple" type="file">
<input name="upload[]" multiple="multiple" type="file">
<input type="submit">
</form>
```

**Comment by askuiop** [comment]
@walkor 使html表单尝试过了： 字段名：file[],   不管是一个input 选中多个文件， 还是每个input 各选中一个文件。
服务端：var_dump($request->file());
输出是：
```
array(1) {
  ["file[]"]=>
  object(Webman\Http\UploadFile)#88 (5) {
    ["_uploadName":protected]=>
    string(15) "unnamed (2).jpg"
    ["_uploadMimeType":protected]=>
    string(10) "image/jpeg"
    ["_uploadErrorCode":protected]=>
    int(0)
    ["pathName":"SplFileInfo":private]=>
    string(28) "/tmp/workerman.upload.1FzygR"
    ["fileName":"SplFileInfo":private]=>
    string(23) "workerman.upload.1FzygR"
  }
}

```

**Comment by walkor** [comment]
看起来是workerman没更新。
https://github.com/walkor/Workerman/blob/4a506c1baff5f9ee93aca1649afecdf50d162302/Protocols/Http/Request.php#L566
对比下你本地文件

**Comment by askuiop** [comment]
@walkor 那请问workerman 什么时候发布新的更新？

**Comment by askuiop** [comment]
@walkor  直接更改 Protocols/Http/Request.php  文件 ， 会出现 ErrorException: Undefined index: tmp_name in

**Comment by askuiop** [comment]
ErrorException: Undefined index: tmp_name in
/xxx/webman/vendor/workerman/webman-framework/src/Http/Request.php:103<br />
Stack trace:<br />
#0 /xxx/webman/vendor/workerman/webman-framework/src/Http/Request.php(103): {closure}(8, 'Undefined index...', '/xxx/webm...', 103, Array)<br />
#1 /xxx/webman/app/api/controller/FileUploadController.php(23): Webman\Http\Request->file('file')<br />
#2 /xxx/webman/vendor/workerman/webman-framework/src/App.php(234): app\api\controller\FileUploadController->fileUpload(Object(support\Request))<br />
#3 /xxx/webman/app/api/middleware/AuthCheck.php(153): Webman\App::Webman\{closure}(Object(support\Request))<br />
#4 /xxx/webman/vendor/workerman/webman-framework/src/App.php(228): app\api\middleware\AuthCheck->process(Object(support\Request), Object(Closure))<br />
#5 /xxx/webman/vendor/workerman/webman-framework/src/App.php(313): Webman\App::Webman\{closure}(Object(support\Request))<br />
#6 /xxx/webman/vendor/workerman/webman-framework/src/App.php(150): Webman\App::findRoute(Object(Workerman\Connection\TcpConnection), '/json/file/uplo...', 'POST/json/file/...', Object(support\Request))<br />
#7 /xxx/webman/vendor/workerman/workerman/Connection/TcpConnection.php(637): Webman\App->onMessage(Object(Workerman\Connection\TcpConnection), Object(support\Request))<br />
#8 /xxx/webman/vendor/workerman/workerman/Events/Select.php(293): Workerman\Connection\TcpConnection->baseRead(Resource id #208)<br />
#9 /xxx/webman/vendor/workerman/workerman/Worker.php(2430): Workerman\Events\Select->loop()<br />
#10 /xxx/webman/vendor/workerman/workerman/Worker.php(1554): Workerman\Worker->run()<br />
#11 /xxx/webman/vendor/workerman/workerman/Worker.php(1384): Workerman\Worker::forkOneWorkerForLinux(Object(Workerman\Worker))<br />
#12 /xxx/webman/vendor/workerman/workerman/Worker.php(1358): Workerman\Worker::forkWorkersForLinux()<br />
#13 /xxx/webman/vendor/workerman/workerman/Worker.php(542): Workerman\Worker::forkWorkers()<br />
#14 /xxx/webman/start.php(156): Workerman\Worker::runAll()<br />
#15 {main}

**Comment by walkor** [comment]
![image](https://user-images.githubusercontent.com/6073368/132812282-1e803a96-b003-4c73-b8de-f6dd2a067917.png)

**Comment by askuiop** [comment]
中间忙其他事情去了， 直接更改源码，使用你修改后代码， 出现的错误

**Comment by askuiop** [comment]
@walkor  刚更新了 - Downloading workerman/webman-framework (v1.0.18)  已经可以了
