### ISSUE TITLE
有办法创建全局变量吗

### ISSUE THREAD

**Issue by mengdodo** [walkor/webman#208]
要实现一个聊天室敏感词过滤，需要读本地的一个敏感词库，控制器里面每次接收到请求后需要fopen读这个文件到类中去。

有没有办法全局加载，在进程启动的时候让我挂进去，这样控制器接收到请求后不需要再去读文件加载？

**Comment by amibk** [comment]
我立马想到的是创建一个类然后弄个静态方法，类里面创建一个私有的静态变量，调用这个静态方法检测私有静态变量是否赋值，没有就读取赋值，有就直接返回，静态类变量在常驻进程里是不会被回收的。

我只是想法没有实践过，你可以试试，当然看看有没有人能给出更好的方案，这个我觉得很简单吧不是个啥问题

**Comment by mengdodo** [comment]
> 我立马想到的是创建一个类然后弄个静态方法，类里面创建一个私有的静态变量，调用这个静态方法检测私有静态变量是否赋值，没有就读取赋值，有就直接返回，静态类变量在常驻进程里是不会被回收的。
> 
> 我只是想法没有实践过，你可以试试，当然看看有没有人能给出更好的方案，这个我觉得很简单吧不是个啥问题

是可以这么实现，我去试试吧，不过要是webman启动的时候能给个地方让我自定义全局变量就更好了

**Comment by mengdodo** [comment]
```
$sensitiveHandle = new SensitiveHelper();

function SensitiveHandle()
{
    global $sensitiveHandle;
    if ($sensitiveHandle === null) {
        $wordFilePath    = './words.txt';
        $sensitiveHandle = SensitiveHelper::init()->setTreeByFile($wordFilePath);
    }

}
```
