### ISSUE TITLE
有些返回客户端的json封装在函数里 。。。没办法返回到客户端了 有什么方法解决吗

### ISSUE THREAD

**Issue by a6965921** [walkor/webman#213]
有些返回客户端的json封装在函数里 。。。没办法返回到客户端了 有什么方法解决吗         如果都写在控制器 就会出现控制器重复代码了

**Comment by walkor** [comment]
问题描述的太模糊了，大家看不懂你在说什么。
如果还有问题请提供详细的描述，比如代码片段，想要的效果，实际效果。配上必要的代码和截图。
