### ISSUE TITLE
中间件语法错误了

### ISSUE THREAD

**Issue by a6965921** [walkor/webman#214]
![image](https://user-images.githubusercontent.com/1198840/125386403-cdc5ea00-e3ce-11eb-9cab-4d0adfbe8f46.png)

**Comment by a6965921** [comment]
https://www.workerman.net/doc/webman#/middleware?id=%e7%a4%ba%e4%be%8b%ef%bc%9a%e7%94%a8%e6%88%b7%e8%ba%ab%e4%bb%bd%e9%aa%8c%e8%af%81%e4%b8%ad%e9%97%b4%e4%bb%b6

**Comment by walkor** [comment]
感谢反馈。已经修复
