### ISSUE TITLE
rabbitmq 队列问题

### ISSUE THREAD

**Issue by weijer** [walkor/webman#217]
现在有 workerman/stomp 实现了Stomp客户端，可以与 rabbitmq  通信实现消息队列。
我看到你还写了个 workerman/rabbitmq 组件，这两个组件使用场景有啥区别。

**Comment by walkor** [comment]
通讯协议不同，一个是stomp协议，一个是amqp协议

**Comment by weijer** [comment]
好的谢谢回复
