### ISSUE TITLE
webman可以整合GatewayWorker 吗？

### ISSUE THREAD

**Issue by li914** [walkor/webman#218]
大佬，webman可以整合GatewayWorker 吗？ 可以给出一个示例吗？

**Comment by li914** [comment]
`    // register 进程
    'register'  => [
        'handler'  => \GatewayWorker\Register::class,
        'listen' => 'text://0.0.0.0:1236',
        'name' => 'RegisterWorker'
    ],
    // bussiness 进程
    'bussiness'  => [
        'handler'  => \GatewayWorker\BusinessWorker::class,
        'registerAddress' => '127.0.0.1:1236',
        'count' => 2,
        'eventHandler' => '\process\Event',
        'name' => 'BusinessWorker',
    ],
    // gateway 进程
    'gateway'  => [
        'handler'  => \GatewayWorker\Gateway::class,
        'constructor' => ['websocket://0.0.0.0:9091'],
        'listen' => 'websocket://0.0.0.0:9091',
        'lanIp' => '127.0.0.1',
        'registerAddress'  => '127.0.0.1:1236',
        'name'  => 'GatewayWorker',
        'count'  => 2,
        'startPort'  => 2300,
    ],`

这是配置的信息，运行就报错， PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, cannot access protected method GatewayWorker\BusinessWorker::onWorkerStart() in   因为是 protected

**Comment by walkor** [comment]
他们2个是不同的项目，就类似redis和mysql，没必要把代码耦合在一起。需要的时候互相调用就行。不清楚你为什么要把他们整合起来？

**Comment by li914** [comment]
好的，谢谢大佬，

这边原来是想直接在webman中使用GatewayWorker，这样子就可以复用数据库方法了，不用单独做数据库连接等等重复操作
