### ISSUE TITLE
worker进程内存占用很高

### ISSUE THREAD

**Issue by weijer** [walkor/webman#222]
worker进程内存占用很高，怎么排查正常不正常。

**Comment by walkor** [comment]
很高是多高？
运行 php start.php status 截图下

**Comment by weijer** [comment]
![image](https://user-images.githubusercontent.com/12838756/130018684-0301f907-db1d-4e8c-a38a-cda141a0071b.png)

**Comment by walkor** [comment]
100多M应该不正常。可能业务哪里有内存泄漏。
如果接口不多的话可以自己压测下，看下哪个接口泄漏。
如果排查不到设置下max_request 为5000或者10000，这样进程请求到一定数量时会自动reload释放内存

**Comment by weijer** [comment]
看样子是 swoole tracker 锅！关闭后内存正常了
![2](https://user-images.githubusercontent.com/12838756/130551804-936eed10-b491-481d-b45a-c5be7cbb1b8c.png)

**Comment by weijer** [comment]
这是开启  swoole tracker 
![Uploading 1.png…]()

**Comment by weijer** [comment]
这是开启 swoole tracker
![1](https://user-images.githubusercontent.com/12838756/130551875-0a68016d-b9b2-4ff3-95f3-be3d7ce32fed.png)

**Comment by Maoxp** [comment]
你这个不是同一个程序吧。进程数也不一样
