### ISSUE TITLE
mysql连接问题

### ISSUE THREAD

**Issue by MastersOfWar** [walkor/webman#224]
控制器代码
    public function index(Request $request)
    {
        var_dump($request->all());
        var_dump(Db::table('test')->get());
        return response('hello webman');
    }

    public function s()
    {
        Db::table('test')->selectRaw('sleep(10)')->get();
        return response('123456');
    }

先请求s再请求index  两个请求都耗时10s

**Comment by MastersOfWar** [comment]
应该一个请求一个连接 或者使用连接池

**Comment by walkor** [comment]
webman设计的时候就是阻塞式IO，无法使用连接池。
webman是每个进程顺序处理请求，多进程并发处理请求。如果2个请求刚好被同一个进程处理，前一个请求处理完才会处理下一个请求，如果前一请求耗时，则会影响这个进程下一个请求处理时间。如果2个请求是被分配到不同进程，那么将会是并发处理，互不影响。

如果有慢业务，建议走队列或者专门开一组进程处理慢业务。
