### ISSUE TITLE
命令行模式 Aborted connection 67 to db: 'webman' user: 'root' host: 'localhost' (Got an error reading communication packets)

### ISSUE THREAD

**Issue by my3306** [walkor/webman#245]
官方文档地址：https://www.workerman.net/doc/webman#/components/console

当数据量较大时，采用 chunkById 分块处理，会在中途 抛出 alarm 退出。查看MySQL报错日志，如标题所示。

**Comment by walkor** [comment]
这个你得到 symfony/console 或者 illuminate/database 项目发issue。

发issue时注意详细描述问题，比如给出所有的错误截图包括终端的错误数据库错误，重现示例代码。
