### ISSUE TITLE
静态资源访问 不识别.well-know 这个文件夹

### ISSUE THREAD

**Issue by a6965921** [walkor/webman#246]
我往.well-know  隐藏文件夹放入文件 结果访问不了 提示403 forbidden              因为我在做HTTPS证书验证 所以需要用到隐藏文件夹

**Comment by walkor** [comment]
打开 config/static.php，将`app\middleware\StaticFile::class` 注释掉，类似这样
```php
return [
    'enable'     => true,
    'middleware' => [ 
        //app\middleware\StaticFile::class,
    ],
];
```
这个静态文件中间件屏蔽了`.`开头的静态文件的访问，因为这类文件可能包含隐私数据，比如 `.env` `.gitignore` `.git/config`。如果你的public下没有`.`开头的隐私文件可以不需要开启它。
