### ISSUE TITLE
多租户应用，每个进程都可能需要维护所有租户的数据库连接？

### ISSUE THREAD

**Issue by lanrenbulan** [walkor/webman#247]
应用是多租户模式，每个租户是不同的数据库，那是不是每个进程都有可能需要创建与租户数量相同的数据库连接呢？

虽然每个连接是根据请求时创建的单例，那一旦租户数量起来后，会不会对应用服务器造成性能影响？因为每个进程都有可能创建所有租户的数据库连接，每个进程的最大连接 = 租户数量 * 进程数量。以现有规模的租户数量算，就是 500 * 10 = 5000了

**Comment by walkor** [comment]
如果你的数据都是装在一个mysql里，一个进程连一个连接就可以，使用的时候可以用 use db语句切换数据库。
如果数据库分散在不同的服务器上，可以采用使用完连接就关闭的策略，减少连接数。
