### ISSUE TITLE
模板可否支持多套模板 ？

### ISSUE THREAD

**Issue by dafa168** [walkor/webman#250]
config/view.php  可以设置模板引擎，是否可以设置具体的模板路径和多套模板呢？

**Comment by walkor** [comment]
多套模版直接调用 support/view/下的类的render方法，路径不符合需求可以在 support/view/下 添加自己的视图类，增加路径参数。

**Comment by dafa168** [comment]
> 多套模版直接调用 support/view/下的类的render方法，路径不符合需求可以在 support/view/下 添加自己的视图类，增加路径参数。

  好的，已经打算这么实现了。谢谢。
