### ISSUE TITLE
数组格式提交的字段,只能获取到一个数值.而不是一个数组数据

### ISSUE THREAD

**Issue by settime** [walkor/webman#256]
提交的数据格式为:

array[] : 1
array[] : 2
array[] : 3

改动  Workerman\Protocols\Http\Request   parseUploadFiles()函数
  大约在550行, 原代码:
$this->_data['post'][$match[1]] = $boundary_value;

  改动后代码:

if (strpos($match[1],'[]')){
     $this->_data['post'][$match[1]][] = $boundary_value ;
  }else{
     $this->_data['post'][$match[1]] = $boundary_value;
  }

**Comment by walkor** [comment]
`multipart/form-data` 表单post提交数组已经在支持，将在workerman下个版本发布。
非`multipart/form-data` 表单post数组之前就是支持的，如果你只是想post数据，不需要上传文件，可以使用普通表单的方式上传。
