### ISSUE TITLE
支持多级控制器吗

### ISSUE THREAD

**Issue by cshaptx4869** [walkor/webman#257]
你好，请问webman支持像tp一样的 多级控制器吗 比如 `app/index/controller/user/Blog.php` 控制器，对应访问 `/index/user.blog/index`

**Comment by walkor** [comment]
支持， 参考手册 https://www.workerman.net/doc/webman/multiapp.html

**Comment by cshaptx4869** [comment]
十分感谢！参照手册中的**多应用路由自动解析**部分，然后基于doctrine/annotations写了一个路由注解解析插件。插件会读取所有控制器上的路由注解然后注册为路由。这样就不用担心目录结构是怎么样的了
