### ISSUE TITLE
你好，请问可以支持同时监听其他端口，支持websocket吗

### ISSUE THREAD

**Issue by avriltank** [walkor/webman#26]
一直用workman，很稳定，无意间看到这款框架，准备用来开发新项目。新项目有用到主动推送到客户端websocket，现在这款框架支持同时监听其他端口，用来为websocket服务吗

**Comment by walkor** [comment]
webman 也可以像workerman那样监听websocket。参见手册 https://www.workerman.net/doc/webman#/process

**Comment by avriltank** [comment]
非常给力！谢谢大佬，看文档没看到这里

**Comment by cexll** [comment]
提问, webman可以接入Gateway吗, 具体配置应该怎么设置呢,

**Comment by walkor** [comment]
http://doc2.workerman.net/work-with-other-frameworks.html

**Comment by cexll** [comment]
> http://doc2.workerman.net/work-with-other-frameworks.html

在 `process` 配置文件
```php
use GatewayWorker\Lib\Gateway;

public function onConnect($client_id)
{
        echo "onConnect\n";
}
public function onMessage($client_id , $message)
{
        Gateway::sendToCurrentClient($message);
}
```
`config/process.php`
```php
'websocket'  => [
        'handler'  => process\GatewayWebsocket::class,
        'listen' => 'websocket://0.0.0.0:8888',
        'count'  => 10,
    ],
```

```php
php start.php start
```
这样启动Gateway, 想实现这种, 在其他demo里面出了`Business` 和 `Register` 应该是缺少了这两个(? )

**Comment by walkor** [comment]
把webman的代码和gatewayWorker融合没有什么意义。如果你需要webman里某个组件，可以直接composer安装使用。

**Comment by cexll** [comment]
不是, 是想webman结合Gateway, 有方便的Uid操作

**Comment by cexll** [comment]
close

**Comment by cexll** [comment]
麻烦主动close一下
