### ISSUE TITLE
How to get dynamic base url 

### ISSUE THREAD

**Issue by haidarvm** [walkor/webman#263]
I try to use webman with docker but got failed Cannot assign IP Address because I use IP (192.168.1.18) base_url in ENV
So how to get dynamic Base url function like  $request->header('host')

I couldn't use `$request->header('host')`  in `app/functions.php`

So, is thereos any simple function to get dynamic host IP like `url()` in laravel or `base_url()` in codeigniter ?

I need it to call assets static files js, img, css, etc
`<link href="<?=base_url();?>assets/css/all.min.css" rel="stylesheet" />`

**Comment by walkor** [comment]
> Cannot assign IP Address because I use IP (192.168.1.18)

Listen `0.0.0.0` instead of `192.168.1.18`.

> I couldn't use `$request->header('host')` in `app/functions.php`

I don't know why you couldn't use `$request->header('host')`. I think use `$request->header('host')` to get host is the right way.

**Comment by haidarvm** [comment]
Ok now I got it, have to be like this

`function base_url() {
    $request = request();
    $base_url = 'http://'.$request->header('host').'/';
    return $base_url;
}`
