### ISSUE TITLE
BUG parse raw "FormBoundary"

### ISSUE THREAD

**Issue by TransTechService** [walkor/webman#264]
Pars send data:  - OK
`------WebKitFormBoundaryv2Uv7gYNDVAWbKia
Content-Disposition: form-data; name="excel"; filename="id_rsa.ppk"
Content-Type: application/octet-stream

PuTTY-User-Key-File-2: ssh-rsa
Encryption: none
Comment: imported-openssh-key
Public-Lines: 6
AAAAB3NzaC1yc2EAAAADAQABAAABAQDIZ78PyvILIguKATd2FeLyVlMzmd4DKpG+
ki0h3S5BuVX5On8xZaxB/dbP0Zp0reQwB26QT3tDW1RUnbLXsw2jmEAbN22bicIJ
BKaqrAyeHJiH9KO0A1jCLsxyDx7+fN6VNuo+TNIvecWhFWstc+9seXVuS20neFn7
mWZZvBXHKoNefMUWFzJYAjj5od6p/PD/gYs756t2AJ3ngiYR/OQMjXPmHFgWDXb1
BFaix1IQBrn68rZyfMCOk/D5AugmRrrz+Ys/dFBs4qXvjrzBEgmVzonideZzrBVb
SFCe2XyTP9+Wx5mPY80vCy+fDMZFJHiE2vCOPWaT2VCGhq1JKAiZ
Private-Lines: 14
AAACAG6mYaa9niCpfoeHHnEzqme1ZCD0jtFeurPnD8ZH0hd11lNSihHjGlYham66
QzazIG+oWtKRH/TTw18o5ysTcK9oC9U7KGidiiXijIdlkV3nWgyO9agZxPMKVdWQ
JcPE3BC1Dmaxkcemy4iiQ9gH0CUrdrwcJzuIxt4VF57qKzFr+zmmrINr1CVdU8LG
O1pgzeSGo3iBjGOUDw+/VSs7F+3VhsJJ4Epn05gWeRfHoLNLpPNE4DZPl1LgpFAy
08x2IHNGIqM4xEweJq3lGkYJ2bY79xV2mnREbrAsGBkR4sNHOU7X1gh7djueCaMc
cqn/dqjukTsVqdmkCTt/MdBKowEAAACBAPtxggPeNGnEm4ATIWRNkuvHJgFJ9Cjq
UdLfWvZXw8aXwsJjKTGc6FwJ0AWpvrkHtlZWh52PQ69uWHOAC4RrkD4Yl/xef0ry
kmmayGGG7dj9FOfd9TsEhBz4CvGM/MBFivISMBC8rnA+Uz/B3pMUkcVUc4fmRBrU
WAcwSpab2TT5AAAAgQDMCXaTcafpD2pkp0vKl2qerSMExqdQx7mnx5t3uvT/iZ+q
6X5vF/VNELM40yoWFh1LKgpcVkRTTpKATbXXjFCfV9YF+s4vNJwZheWKXU+UxNdd
prUt2BUm1+H8HwAL/g8rUpC47A3FbUK03AbUnktlW14ImstWuAce2WP87cF4oQAA
AIB8aVEUhLFC3rJgueOqSxGYKl6J0lyabdrLkuZeMGs8/k1QB3OXVig4ftShxU25
D8w7VU1JT/JSwxqoMyC8QNC6a+AC9rOcvEla6fzem9NeDEz/G6JyLPOOfBeFAEbK
wTdE+7LowcJI+VRCUBY4ut5UWYUWRDEuooYdNg9baA/0KQ==
Private-MAC: f923580e6fe3a949826d7d0965a21fae8d94564d

------WebKitFormBoundaryv2Uv7gYNDVAWbKia
Content-Disposition: form-data; name="subdivision"

Select...
------WebKitFormBoundaryv2Uv7gYNDVAWbKia--
`

Pars send data:  - ERROR

`------WebKitFormBoundaryjTZMYPxpam1AKDBX
Content-Disposition: form-data; name="save_settings"

1
------WebKitFormBoundaryjTZMYPxpam1AKDBX
Content-Disposition: form-data; name="field[0]"

sort_id
------WebKitFormBoundaryjTZMYPxpam1AKDBX
Content-Disposition: form-data; name="field[1]"

sort_name
------WebKitFormBoundaryjTZMYPxpam1AKDBX
Content-Disposition: form-data; name="field[2]"

sort_inn
------WebKitFormBoundaryjTZMYPxpam1AKDBX
Content-Disposition: form-data; name="field[3]"

sort_ogrn
------WebKitFormBoundaryjTZMYPxpam1AKDBX
Content-Disposition: form-data; name="field[4]"

sort_action
------WebKitFormBoundaryjTZMYPxpam1AKDBX
Content-Disposition: form-data; name="show[id]"

on
------WebKitFormBoundaryjTZMYPxpam1AKDBX
Content-Disposition: form-data; name="show[name]"

on
------WebKitFormBoundaryjTZMYPxpam1AKDBX
Content-Disposition: form-data; name="show[inn]"

on
------WebKitFormBoundaryjTZMYPxpam1AKDBX
Content-Disposition: form-data; name="show[ogrn]"

on
------WebKitFormBoundaryjTZMYPxpam1AKDBX
Content-Disposition: form-data; name="show[action]"

on
------WebKitFormBoundaryjTZMYPxpam1AKDBX--`

Return - 
`array(11) {
  ["save_settings"]=>
  string(1) "1"
  ["field[0]"]=>
  string(7) "sort_id"
  ["field[1]"]=>
  string(9) "sort_name"
  ["field[2]"]=>
  string(8) "sort_inn"
  ["field[3]"]=>
  string(9) "sort_ogrn"
  ["field[4]"]=>
  string(11) "sort_action"
  ["show[id]"]=>
  string(2) "on"
  ["show[name]"]=>
  string(2) "on"
  ["show[inn]"]=>
  string(2) "on"
  ["show[ogrn]"]=>
  string(2) "on"
  ["show[action]"]=>
  string(2) "on"
}`

**Comment by walkor** [comment]
Please upgrade workerman to v4.0.25 or greater.

**Comment by TransTechService** [comment]
Thank you, now everything works out well, any level of nesting!
