### ISSUE TITLE
tryToGracefulExit的进程退出问题

### ISSUE THREAD

**Issue by HyMax** [walkor/webman#267]
`    protected static function tryToGracefulExit()
    {
        if (static::$_gracefulStopTimer === null) {
            static::$_gracefulStopTimer = Timer::add(1, function () {
                if (\count(static::$_worker->connections) === 0) {
                    Worker::stopAll();
                }
            });
        }
    }`
我看这段代码，是在请求数达到 max_request 配置的值之后，通过定时器判断当前请求连接为0 的情况下进行进程的重启，我想知道，什么情况下 static::$_worker->connections 会为0，我自己测试用浏览器请求接口，达到请求数并且接口没有再进行请求了，workerman的几个进程ID 都是不变的。 还有，这段代码不能改为如下吗？直接关闭得了。
`    protected static function tryToGracefulExit()
    {
        Worker::stopAll();
    }`

**Comment by walkor** [comment]
为了提高性能，浏览器请求完毕后不会立刻关闭连接，连接会保持一端时间以便下个请求复用连接。时间大概在一分钟左右。具体保持多长时间可能不同浏览器实现不同。
如果不判断当前连接数直接关闭进程，极端情况会导致请求丢失。

**Comment by HyMax** [comment]
> 为了提高性能，浏览器请求完毕后不会立刻关闭连接，连接会保持一端时间以便下个请求复用连接。时间大概在一分钟左右。具体保持多长时间可能不同浏览器实现不同。 如果不判断当前连接数直接关闭进程，极端情况会导致请求丢失。

好的，那请教添加了一个持久的定时器进行监听，从这个定时器上面看，好像第一次达到 max_request 之后，就会不停的判断 连接数如果等于 0  就重启了呀。  我意思是这个持久化的定时器是否会导致第一次达到 max_request 之后，每次连接数为0 就重启，而不是等到第二次达到 max_request  之后再重启。

**Comment by HyMax** [comment]
我想了下，文档中  『定时器是在当前进程中运行的』  这句话， 是不是只要进程重启了，那这个定时器也就随之消失了。

**Comment by walkor** [comment]
对，进程重启了定时器就消失了。

**Comment by HyMax** [comment]
> 对，进程重启了定时器就消失了。

大佬，我发现 webman 里面如果redis挂了，是不会重连的，那么，好像用 workeman/redis  这个组件更靠谱啊。 不然redis不支持重连很麻烦。

**Comment by walkor** [comment]
之前专门测试过，会重连。

**Comment by HyMax** [comment]
> 之前专门测试过，会重连。

我知道了，我用的缓存驱动ThinkCache，类型是 redis，然后把redis重启，就发现没重新连接了。
