### ISSUE TITLE
mysql慢查询阻塞当前进程

### ISSUE THREAD

**Issue by ww365610866** [walkor/webman#269]
只启用了一个worker,在控制器中$name = Db::table('fans')->where('id',1)->selectRaw('avatar,sleep(3) as sleep')->get();模拟慢查询,导致当前进程阻塞,打开其他浏览器访问其他控制器也会阻塞,不是说是异步io模型么,感觉都是同步的啊

**Comment by walkor** [comment]
workerman本身的io是非阻塞的，但是php的pdo扩展是阻塞操作，这个workerman无法控制。

**Comment by ww365610866** [comment]
> workerman本身的io是非阻塞的，但是php的pdo扩展是阻塞操作，这个workerman无法控制。

mysql,redis是项目必用的,这块阻塞会导致整体性能拉跨...有啥推荐的解决方案么?

**Comment by walkor** [comment]
redis一般都很快，不用担心。数据库要优化好sql，不要有慢查询。
如果你的业务有大量数据库IO操作，多开一些进程，比如cpu的2-5倍，让请求尽量分摊到多个进程可以缓解这个问题。

如果sql慢，即使mysql是异步的，也无法有效提高并发。比如sql 3秒返回数据，这3秒有3000个请求过来，需要与数据库建立9000个连接才能应对，连接数已经爆了，再加上这么多的慢查询，数据库cpu估计也100%当机了。
