### ISSUE TITLE
为什么中间件不会触发了

### ISSUE THREAD

**Issue by a6965921** [walkor/webman#270]
`Route::any('/moban/testurl', [app\controller\Moban::class, 'testurl'])->middleware([
       app\middleware\RequestInfo::class,
]);`
`    public function testurl(Request $request){
        return 111;
    }`
为什么中间件不会触发了。。没报错
`class RequestInfo implements MiddlewareInterface
{
    public function process(Request $request, callable $next): Response
    {

         return response(commonajax(433, 'test'));
        $insertdata            = array();
        $insertdata['poststr'] = $request->post();
        $insertdata['openid']  = $request->input('openid');
        $insertdata['time']    = time();
        $begintime=time();

        $response = $next($request);
        $endtime=time();
        $duringTime=$endtime-$begintime;
        $insertdata['during_time']=$duringTime;
        $insertdata['url_request']=$request->fullUrl();
        commoninsertinfo($insertdata,'request_info');

        return $response;

    }
}
`

**Comment by walkor** [comment]
触发不了页面显示什么？

**Comment by a6965921** [comment]
页面就正常显示
public function process(Request $request, callable $next): Response
{
就是这个没触发 

> 触发不了页面显示什么？

**Comment by walkor** [comment]
把项目打包发一份吧。不然没办法定位。

**Comment by a6965921** [comment]
刚仔细看了下 是链接错了  后面多加了/就不行了
