### ISSUE TITLE
关于webman多线程的疑问

### ISSUE THREAD

**Issue by a6965921** [walkor/webman#275]
默认webman应该开了8个线程
我服务器centos 机子是4核CPU
我测试了下
`   public function sdssdd(Request $request){
        sleep(2);
        echo PHP_EOL;
        echo time();
    }`
    ab -n 16 -c 16  http://127.0.0.1:8789/moban/sdssdd
    我16个并发测试下
    1642743375
1642743377
1642743377
1642743377
1642743377
1642743377
1642743377
1642743379
1642743379
1642743379
1642743379
1642743379
1642743379
1642743381
1642743381
1642743381
1642743381
   
结果真实际不一样哈  不是应该8个线程 可以处理8个并发吗

**Comment by walkor** [comment]
连接默认是抢占分配，如果需要平均分配，需要在 config/server.php 里设置 `reusePort => true`，并restart重启webman

**Comment by a6965921** [comment]
> 连接默认是抢占分配，如果需要平均分配，需要在 config/server.php 里设置 `reusePort => true`，并restart重启webman

是不是设置平均分配高并发性能要比抢占分配 性能好

**Comment by walkor** [comment]
看情况，如果进程开得过多，每个进程都处理业务，会有cpu开销，对性能有一定影响。进程数建议开cpu核2-4倍。如果业务处理速度慢，进程就多开一些，平均分配性能会更好一些。
