### ISSUE TITLE
上传文件时报错 Undefined index: type

### ISSUE THREAD

**Issue by gumphp** [walkor/webman#276]
控制器代码
```
class Device
{
    public function upload(Request $request)
    {
        $file = $request->file('file');
    }
}
```

报错如下：
[2022-01-21 15:11:14] default.ERROR: Undefined index: type {"exception":"ErrorException: Undefined index: type in /Users/chen/Code/www/webman/vendor/workerman/webman-framework/src/Http/Request.php:127

在Request.php 127行 parseFile 方法 print_r($file)
```
Array
(
    [name] => 
    [tmp_name] => /private/var/folders/zg/jt3t90p54t3199md1d3xdvq00000gn/T/workerman.upload.NdyqKR
    [size] => 0
    [error] => 7
)
```

**Comment by Tinywan** [comment]
这是你后面业务代码的问题吧
```
$file = $request->file('file');
if (!$file->isValid()) {
    throw new BadRequestHttpException('无效的文件');
}
```

**Comment by gumphp** [comment]
> 这是你后面业务代码的问题吧
> 
> ```
> $file = $request->file('file');
> if (!$file->isValid()) {
>     throw new BadRequestHttpException('无效的文件');
> }
> ```

应该是 parseFile方法参数 $file 没有type这个key，临时在support/Request里重写了这个方法解决的

**Comment by Tinywan** [comment]
这是你上传方式不合适吧！我这边都是么有问题的

![image](https://user-images.githubusercontent.com/14959876/150495916-31ec6781-0c17-42d9-a0b5-c458329e6c5f.png)

**Comment by gumphp** [comment]
> 这是你上传方式不合适吧！我这边都是么有问题的
> 
> ![image](https://user-images.githubusercontent.com/14959876/150495916-31ec6781-0c17-42d9-a0b5-c458329e6c5f.png)

找到问题了，上传时指定了参数file，但是没提交上传的文件，就报这个错误了，是我的问题，应该校验上传文件

**Comment by Tinywan** [comment]
问题解决就好啦！
