### ISSUE TITLE
webman daemon mode 进程异常退出

### ISSUE THREAD

**Issue by hollisho** [walkor/webman#278]
daemon mode启动之后，进程如果有echo 、 var_dump之类的输出，就会无限重启

**Comment by hollisho** [comment]
worker[sync_data:19580] exit with status 65280
2022-01-22 16:12:23 pid:19470 worker[mqtt:19588] exit with status 65280
2022-01-22 16:12:24 pid:19593 Worker[19593] process terminated
2022-01-22 16:12:24 pid:19601 Worker[19601] process terminated
2022-01-22 16:12:25 pid:19470 worker[sync_data:19593] exit with status 65280
2022-01-22 16:12:25 pid:19470 worker[mqtt:19601] exit with status 65280
2022-01-22 16:12:26 pid:19606 Worker[19606] process terminated
2022-01-22 16:12:26 pid:19611 Worker[19611] process terminated
2022-01-22 16:12:27 pid:19470 worker[sync_data:19606] exit with status 65280
2022-01-22 16:12:27 pid:19470 worker[mqtt:19611] exit with status 65280
2022-01-22 16:12:27 pid:19624 Worker[19624] process terminated
2022-01-22 16:12:27 pid:19619 Worker[19619] process terminated
2022-01-22 16:12:28 pid:19470 worker[mqtt:19624] exit with status 65280
2022-01-22 16:12:28 pid:19470 worker[sync_data:19619] exit with status 65280
2022-01-22 16:12:29 pid:19632 Worker[19632] process terminated
2022-01-22 16:12:29 pid:19637 Worker[19637] process terminated
2022-01-22 16:12:30 pid:19470 worker[mqtt:19632] exit with status 65280
2022-01-22 16:12:30 pid:19470 worker[sync_data:19637] exit with status 65280
2022-01-22 16:12:31 pid:19645 Worker[19645] process terminated
2022-01-22 16:12:31 pid:19650 Worker[19650] process terminated
2022-01-22 16:12:32 pid:19470 worker[mqtt:19645] exit with status 65280
2022-01-22 16:12:32 pid:19470 worker[sync_data:19650] exit with status 65280

**Comment by hollisho** [comment]
环境Workerman version:4.0.26          PHP version:7.4.22

**Comment by walkor** [comment]
运行 `php -v` 截图下，看看是不是用了dev版本

**Comment by hollisho** [comment]
PHP 7.4.22 (cli) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

**Comment by walkor** [comment]
config/server.php里设置成只开一个进程。启动后`php start.php status` 找到这个进程pid，用命令
`strace -s500 -ttp 进程pid` ，然后粘贴下输出，大概能看到为什么进程会退出。

**Comment by hollisho** [comment]
试了一下，看不出什么异常。strace -s500 -ttp 6546
strace: Process 6546 attached
10:53:18.655786 restart_syscall(<... resuming interrupted system call ...>) = 0
10:54:00.586706 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:54:55.587272 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.592464 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.592969 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.593383 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.593695 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.594015 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.594404 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.594730 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.595453 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.595869 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.596288 restart_syscall(<... resuming interrupted restart_syscall ...>) = 3
10:55:20.596714 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.597081 restart_syscall(<... resuming interrupted restart_syscall ...>) = 1225
10:55:20.597924 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.598442 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.598968 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.599359 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.599728 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.600142 restart_syscall(<... resuming interrupted restart_syscall ...>) = 3
10:55:20.600875 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.601187 restart_syscall(<... resuming interrupted restart_syscall ...>) = 4015
10:55:20.602778 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.603334 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.604110 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.604687 restart_syscall(<... resuming interrupted restart_syscall ...>) = 3
10:55:20.605102 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.605483 restart_syscall(<... resuming interrupted restart_syscall ...>) = 1877
10:55:20.606532 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.607164 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.607515 restart_syscall(<... resuming interrupted restart_syscall ...>) = 7265
10:55:20.609468 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.609831 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.610331 restart_syscall(<... resuming interrupted restart_syscall ...>) = 15
10:55:20.621118 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.622443 --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=7265, si_uid=0, si_status=0, si_utime=0, si_stime=0} ---
10:55:20.622996 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.623339 restart_syscall(<... resuming interrupted restart_syscall ...>) = 7265
10:55:20.624064 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.624520 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.625275 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.625658 restart_syscall(<... resuming interrupted restart_syscall ...>) = 3
10:55:20.626191 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.626789 restart_syscall(<... resuming interrupted restart_syscall ...>) = 2333
10:55:20.627822 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.628758 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.629151 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.629648 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.630221 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.630637 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.630888 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.631308 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.631944 restart_syscall(<... resuming interrupted restart_syscall ...>) = 3
10:55:20.632445 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.632765 restart_syscall(<... resuming interrupted restart_syscall ...>) = 6230
10:55:20.635140 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.635602 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.636150 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.636541 restart_syscall(<... resuming interrupted restart_syscall ...>) = 3
10:55:20.637091 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.637720 restart_syscall(<... resuming interrupted restart_syscall ...>) = 6780
10:55:20.639705 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.640171 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.640684 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.641084 restart_syscall(<... resuming interrupted restart_syscall ...>) = 3
10:55:20.641506 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.642014 restart_syscall(<... resuming interrupted restart_syscall ...>) = 1914
10:55:20.643268 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.643839 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.644360 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.644939 restart_syscall(<... resuming interrupted restart_syscall ...>) = 3
10:55:20.645702 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.645988 restart_syscall(<... resuming interrupted restart_syscall ...>) = 2651
10:55:20.647083 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.647851 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.648293 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.649080 restart_syscall(<... resuming interrupted restart_syscall ...>) = 3
10:55:20.649603 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.649904 restart_syscall(<... resuming interrupted restart_syscall ...>) = 1029
10:55:20.650762 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.651190 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.651901 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.652520 restart_syscall(<... resuming interrupted restart_syscall ...>) = 3
10:55:20.653106 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.653680 restart_syscall(<... resuming interrupted restart_syscall ...>) = 3032
10:55:20.654419 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.654947 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.655421 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.655803 restart_syscall(<... resuming interrupted restart_syscall ...>) = 3
10:55:20.656142 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.656613 restart_syscall(<... resuming interrupted restart_syscall ...>) = 1197
10:55:20.657193 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.657640 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.658092 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.660154 restart_syscall(<... resuming interrupted restart_syscall ...>) = 3
10:55:20.661916 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.665267 restart_syscall(<... resuming interrupted restart_syscall ...>) = 845
10:55:20.666104 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.667446 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.668475 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.669034 restart_syscall(<... resuming interrupted restart_syscall ...>) = 3
10:55:20.669600 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.671065 restart_syscall(<... resuming interrupted restart_syscall ...>) = 1737
10:55:20.672749 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.675625 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.676678 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.677244 restart_syscall(<... resuming interrupted restart_syscall ...>) = 3
10:55:20.677748 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.679820 restart_syscall(<... resuming interrupted restart_syscall ...>) = 1281
10:55:20.681110 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.682079 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.684182 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.685129 restart_syscall(<... resuming interrupted restart_syscall ...>) = 3
10:55:20.685612 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.685943 restart_syscall(<... resuming interrupted restart_syscall ...>) = 8820
10:55:20.688389 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.689870 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.690405 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.690867 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.691446 restart_syscall(<... resuming interrupted restart_syscall ...>) = 3
10:55:20.691796 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.692208 restart_syscall(<... resuming interrupted restart_syscall ...>) = 6442
10:55:20.694473 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.694913 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.695708 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.696375 restart_syscall(<... resuming interrupted restart_syscall ...>) = 3
10:55:20.696769 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.697357 restart_syscall(<... resuming interrupted restart_syscall ...>) = 7834
10:55:20.699785 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.700243 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.700740 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.701291 restart_syscall(<... resuming interrupted restart_syscall ...>) = 3
10:55:20.701640 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.701890 restart_syscall(<... resuming interrupted restart_syscall ...>) = 958
10:55:20.702779 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.703579 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.703948 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.704390 restart_syscall(<... resuming interrupted restart_syscall ...>) = 3
10:55:20.705232 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.705543 restart_syscall(<... resuming interrupted restart_syscall ...>) = 1085
10:55:20.706298 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.707223 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.707624 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.708403 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.708988 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.709323 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.709844 restart_syscall(<... resuming interrupted restart_syscall ...>) = 3
10:55:20.710925 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.711263 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.711558 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.712028 restart_syscall(<... resuming interrupted restart_syscall ...>) = 101
10:55:20.712803 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.713380 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.713741 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.714207 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.715277 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.715826 restart_syscall(<... resuming interrupted restart_syscall ...>) = 4
10:55:20.716175 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.716409 restart_syscall(<... resuming interrupted restart_syscall ...>) = 773
10:55:20.718105 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.718592 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.719063 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.719441 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.720355 restart_syscall(<... resuming interrupted restart_syscall ...>) = 4
10:55:20.720748 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.721315 restart_syscall(<... resuming interrupted restart_syscall ...>) = 423
10:55:20.722090 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.722580 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.723309 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.723743 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.724416 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.724762 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.725141 restart_syscall(<... resuming interrupted restart_syscall ...>) = 4
10:55:20.725808 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.726063 restart_syscall(<... resuming interrupted restart_syscall ...>) = 7273
10:55:20.727505 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.727959 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.728419 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.728949 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.729421 restart_syscall(<... resuming interrupted restart_syscall ...>) = 4
10:55:20.730217 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.730634 restart_syscall(<... resuming interrupted restart_syscall ...>) = 2380
10:55:20.731625 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.732352 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.732882 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.733254 restart_syscall(<... resuming interrupted restart_syscall ...>) = 4
10:55:20.733642 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.734040 restart_syscall(<... resuming interrupted restart_syscall ...>) = 881
10:55:20.735897 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.736699 restart_syscall(<... resuming interrupted restart_syscall ...>) = 4
10:55:20.737352 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.738134 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.738647 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.739516 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.739884 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.740654 restart_syscall(<... resuming interrupted restart_syscall ...>) = 5
10:55:20.741035 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.741515 restart_syscall(<... resuming interrupted restart_syscall ...>) = 32590
10:55:20.747853 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.748299 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.748898 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.749504 restart_syscall(<... resuming interrupted restart_syscall ...>) = 5
10:55:20.749870 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.750756 restart_syscall(<... resuming interrupted restart_syscall ...>) = 22074
10:55:20.753094 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.753620 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.754358 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.754781 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.755426 restart_syscall(<... resuming interrupted restart_syscall ...>) = 5
10:55:20.755911 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.756316 restart_syscall(<... resuming interrupted restart_syscall ...>) = 24826
10:55:20.758022 restart_syscall(<... resuming interrupted restart_syscall ...>) = 2594177024
10:55:20.761774 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.762801 restart_syscall(<... resuming interrupted restart_syscall ...>) = 168
10:55:20.763250 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.764108 restart_syscall(<... resuming interrupted restart_syscall ...>) = 6546
10:55:20.764477 restart_syscall(<... resuming interrupted restart_syscall ...>) = 6546
10:55:20.764779 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.765134 restart_syscall(<... resuming interrupted restart_syscall ...>) = 4
10:55:20.765726 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.765970 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.766566 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.767294 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.767912 restart_syscall(<... resuming interrupted restart_syscall ...>) = 61
10:55:20.768491 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.769028 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.769697 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.770324 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.770718 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.771486 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.773602 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.774586 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.775240 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.776049 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.776726 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.777767 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.778561 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.779424 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.780185 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.780899 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.781709 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.782153 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.783069 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.783704 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.784296 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.785213 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.785889 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.786409 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.787490 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.793560 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.794662 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.797124 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.797522 restart_syscall(<... resuming interrupted restart_syscall ...>) = 0
10:55:20.799726 restart_syscall(<... resuming interrupted restart_syscall ...>) = ?
10:55:20.802294 +++ exited with 255 +++

**Comment by hollisho** [comment]
我这边用的是自定义进程。代码如下。把echo那行代码去掉，就正常了
class IpMonitor
{
    public function onWorkerStart(Worker $worker)
    {
        //  每5分钟检测一次盒子ip是否变化
        $deviceNumber = Application::getInstance()->getDeviceNumber();
        Timer::add(300, function () use ($deviceNumber) {
            ServiceFactory::Common()->deviceIpMonitor($deviceNumber);
            echo sprintf("[" . date('Y-m-d H:i:s') . "] %s", "IP监控") . PHP_EOL;
        });
    }
}

**Comment by walkor** [comment]
截图下config/server.php配置

strace没有捕获到执行echo 输出的记录。因为你在onWorkerStart里就输出了，strace的时候已经执行完了echo相关的代码。
不要在进程启动的时候就输出，把输出改成用定时器输出，比如20秒后输出，这样可以捕获到echo的时候进程发生了什么操作。然后再贴下strace的结果。

**Comment by walkor** [comment]
另外看下rutime/log 下有没有什么日志

**Comment by hollisho** [comment]
代码里面用的是定时器输出的。启动后5分钟输出。runtime/log 目录下，stdout.log 和 webman-xxxxx.log没有错误日志，workerman.log只有前面贴出来的exit with status 65280，没有具体错误信息

**Comment by hollisho** [comment]
代码里面用的是定时器输出的。启动后5分钟输出。runtime/log 目录下，stdout.log 和 webman-xxxxx.log没有错误日志，workerman.log只有前面贴出来的exit with status 65280，没有具体错误信息

**Comment by hollisho** [comment]
return [
    'listen'               => 'http://0.0.0.0:8787',
    'transport'            => 'tcp',
    'context'              => [],
    'name'                 => 'webman',
    'count'                => 1,
    'user'                 => '',
    'group'                => '',
    'reusePort'            => false,
    'pid_file'             => runtime_path() . '/webman.pid',
    'stdout_file'          => runtime_path() . '/logs/stdout.log',
    'log_file'             => runtime_path() . '/logs/workerman.log',
    'max_package_size'     => 10*1024*1024
];
这个是我这边config/server.php的配置

**Comment by walkor** [comment]
重新创建一个webman项目，不带业务代码echo试下有没有问题。

strace里看到了一个SIGCHLD的信号，看下是不是业务用了pcntl_fork。webman里不允许用pcntl_fork
