### ISSUE TITLE
ab压测 30w数量。2w并发会出现Connection timed out

### ISSUE THREAD

**Issue by dragon-D** [walkor/webman#279]
基本都是20多w就会出现Connection timed out。
服务器。16c、32g
PHP 7.3.15
webman: 1.2.1
日志没看到有有异常

**Comment by walkor** [comment]
按照手册优化下linux内核试下。
https://www.workerman.net/doc/workerman/appendices/kernel-optimization.html

如果还有问题，发下操作系统，截图下压测命令及压测输出内容。

**Comment by dragon-D** [comment]
找到原因了，压测客户端出现了端口用光的情况
