### ISSUE TITLE
beforeAction takes precedence

### ISSUE THREAD

**Issue by ExecPHP** [walkor/webman#280]
beforeAction takes precedence over middleware. It seems to me that this is not entirely true, to call the controller before the middleware. was it meant to be?

**Comment by walkor** [comment]
Webman uses middleware to implement `beforeAction`. If you have multiple middlewares, put the middleware which implementing `beforeAction` behind all other middlewares in the configuration, and `beforeAction` will not take precedence over other middleware.

**Comment by ExecPHP** [comment]
This cannot be done when ActionHook is set as a global class and check middleware is connected in routers.
