### ISSUE TITLE
是否可以默认在 start.php 头部增加 php 解释器？并重命名 start.php 为 webman 或者 start。

### ISSUE THREAD

**Issue by mouyong** [walkor/webman#289]
https://github.com/walkor/webman/blob/56f2fb21c87d42b9f6d203e071b36dd1afb33df9/start.php#L1

问答：https://www.workerman.net/q/7950

```
#!/usr/bin/env php # 这里，在头部增加此行。并重命名 start.php 为 webman 或者 start
<?php

require_once __DIR__ . '/vendor/autoload.php';

<...>
```

**Comment by walkor** [comment]
安装 `webman/console` 后自动生成一个webman可执行文件，支持启动停止等命令。 

由于直接更改启动文件名会影响到已经熟悉使用webman的人，会导致很多不必要的问询，所以webman自身的启动命令暂时保持不变。

**Comment by walkor** [comment]
加了一个 `#!/usr/bin/env php`

**Comment by mouyong** [comment]
什么时候会发布新的版本呢？

**Comment by walkor** [comment]
已经发布了
