### ISSUE TITLE
关于使用laravel orm 抛出连接异常

### ISSUE THREAD

**Issue by pl1998** [walkor/webman#294]
关于使用laravel orm 抛出连接异常

使用webman 安装laravel-orm 接口插入数据和查询数据都正常 orm一直抛出数据库连接错误提示

![image](https://user-images.githubusercontent.com/43993206/156555526-67d28d6d-6f6e-427c-ad89-785941bc944e.png)

**Comment by walkor** [comment]
贴下config/database.php的配置，完整的配置。敏感信息用`****`代替。

**Comment by pl1998** [comment]
![image](https://user-images.githubusercontent.com/43993206/156566297-a13f147a-635e-4ef9-b0c3-d6c645b4c0a7.png)

**Comment by walkor** [comment]
只保留用到的配置，其它没用到的配置如info等删除掉就好了

**Comment by pl1998** [comment]
明白了。。。
