### ISSUE TITLE
1.2.5 支持monolog processors 产生的问题

### ISSUE THREAD

**Issue by tingleiwuyan** [walkor/webman#296]
报错如下:
ErrorException: Undefined index: class in /usr/src/myapp/support/Log.php:84
Stack trace:
#0 /usr/src/myapp/support/Log.php(84): {closure}(8, 'Undefined index...', '/usr/src/myapp/...', 84, Array)
#1 /usr/src/myapp/support/Log.php(72): support\Log::handler('Monolog\\Handler...', Array, Array)
#2 /usr/src/myapp/support/Log.php(53): support\Log::handlers(Array)
#3 /usr/src/myapp/start.php(68): support\Log::channel('default')
#4 /usr/src/myapp/vendor/workerman/workerman/Worker.php(2405): {closure}(Object(Workerman\Worker))
#5 /usr/src/myapp/vendor/workerman/workerman/Worker.php(1542): Workerman\Worker->run()
#6 /usr/src/myapp/vendor/workerman/workerman/Worker.php(1373): Workerman\Worker::forkOneWorkerForLinux(Object(Workerman\Worker))
#7 /usr/src/myapp/vendor/workerman/workerman/Worker.php(1347): Workerman\Worker::forkWorkersForLinux()
#8 /usr/src/myapp/vendor/workerman/workerman/Worker.php(1679): Workerman\Worker::forkWorkers()
#9 /usr/src/myapp/vendor/workerman/workerman/Worker.php(1628): Workerman\Worker::monitorWorkersForLinux()
#10 /usr/src/myapp/vendor/workerman/workerman/Worker.php(544): Workerman\Worker::monitorWorkers()
#11 /usr/src/myapp/start.php(87): Workerman\Worker::runAll()
#12 {main}
建议不要将formatter作为必填项

**Comment by walkor** [comment]
发下你的log配置

**Comment by tingleiwuyan** [comment]
return [
    'default' => [
        'handlers' => [
            [
                'class' => Monolog\Handler\MongoDBHandler::class,
                'constructor' => [
                    new \MongoDB\Client('mongodb://127.0.0.1:27017'),
                    'center',
                    'logs_'.date('Y-m-d'),
                    Monolog\Logger::DEBUG,
                ],
            ],
        ],
        'processors'=>[
            'class'=> new \Monolog\Processor\WebProcessor(),
            #'class'=>new \support\WebProcessor(),
        ]
    ],
];

**Comment by walkor** [comment]
发pr吧

**Comment by tingleiwuyan** [comment]
已提交

**Comment by walkor** [comment]
合并了，等下个版本一起发布
