### ISSUE TITLE
how to use illuminate/database migration

### ISSUE THREAD

**Issue by yekern** [walkor/webman#304]
正在使用illuminate/database 的ORM 想使用 配套的 migration , 封装的比phinx 好用,有什么方法或者方向吗?

**Comment by walkor** [comment]
laravel的 migration 好像没有独立的库吧

**Comment by yekern** [comment]
> laravel的 migration 好像没有独立的库吧

查看代码 和 illuminate/database是在一起的

**Comment by skyfister** [comment]
可以自己创建个migrations表，实现migrate、rollback、seed:run命令，在命令里面调用eloquent的schema类执行数据表的迁移和填充。

**Comment by skyfister** [comment]
请在听到滴的一声后开始留言！
