### ISSUE TITLE
xdebug跟workerman有哪些不兼容的，我本地调试了一下是可以跑的

### ISSUE THREAD

**Issue by Sanit1** [walkor/webman#314]
李亮大大你好，我想问下我本地使用xdebug可以调试webman，我看你的问答中说不兼容

环境：
php  7.4.25

**Comment by walkor** [comment]
windows系统？
可能是xdebug升级支持了

**Comment by Sanit1** [comment]
> windows系统？ 可能是xdebug升级支持了

macOS Monterey 

![image](https://user-images.githubusercontent.com/26242198/171568128-3df68db4-cd67-410b-a0c2-f3671a514d80.png)


php 版本：

PHP 7.4.25 (cli) (built: Oct 23 2021 18:05:05) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v3.1.4, Copyright (c) 2002-2022, by Derick Rethans
    with Zend OPcache v7.4.25, Copyright (c), by Zend Technologies


webman版本：
![image](https://user-images.githubusercontent.com/26242198/171568551-56352ca6-5a83-46e2-a4fd-8ceeebe9e931.png)


目前简单用下来xdebug调试一切正常

**Comment by walkor** [comment]
好的，感谢反馈

**Comment by airqj** [comment]
真是个好消息  
赶紧去测试看看
