### ISSUE TITLE
调试模式不应该和是否使用 daemonize 绑定

### ISSUE THREAD

**Issue by ihipop** [walkor/webman#326]
稍微看了一下代码，调试模式和 daemonize 模式还是有点区别的，比如，调试模式会定时重新加载代码，这个在生产模式不应该有的

https://github.com/walkor/webman/blob/38e5bc80325eaf58e111a3b9b3f9dba92c238470/process/Monitor.php#L53-L56

如果只是终端运行倒也没啥大问题，但是如果涉及到docker,就有问题了

docker的原则是，[建议入口启动的程序应该在前台运行](https://docs.docker.com/engine/reference/builder/#exec-form-entrypoint-example)，否则他就认为程序挂了，然后尝试反复重启。前台运行的程序是否退出也是一个监控指标。

现在 我需要前台运行webman，但是又不能在生产打开调试模式，然而webman关闭调试模式就又和daemonize是绑定的，导致进退两难。

如果用一个其他什么程序前台运行骗骗docker 倒是可以解决，（比如有些人额外运行了个supervisor/tail -f）这就显得多余而且失去了容器健康检查的作用。要知道，在容器集群里面，容器是否活着也是一个监控指标，这个指标默认就是靠监控容器入口进程是否死掉来的。

建议webman的调试模式不应该和是否使用 daemonize 绑定而是单独指定参数开启关闭，这也是通行的做法。

**Comment by walkor** [comment]
https://github.com/walkor/webman/blob/2acbb5d167388d8e8939db40dd71d3e9af5d4589/config/process.php#L37
webman 1.4.7 在config/process.php里增加了参数 `options.enable_file_monitor `用来决定是否开启文件监控
