### ISSUE TITLE
webman  console 应用程序，使用异步http-cilent 报错

### ISSUE THREAD

**Issue by twomiao** [walkor/webman#333]
`PHP Fatal error:  Uncaught Error: Call to a member function add() on null in /mnt/c/users/twomiao/desktop/luckysheet-phpserver/vendor/workerman/workerman/Connection/AsyncTcpConnection.php:213
Stack trace:
#0 /mnt/c/users/twomiao/desktop/luckysheet-phpserver/vendor/workerman/http-client/src/ConnectionPool.php(216): Workerman\Connection\AsyncTcpConnection->connect()
#1 /mnt/c/users/twomiao/desktop/luckysheet-phpserver/vendor/workerman/http-client/src/ConnectionPool.php(76): Workerman\Http\ConnectionPool->create()
#2 /mnt/c/users/twomiao/desktop/luckysheet-phpserver/vendor/workerman/http-client/src/Client.php(145): Workerman\Http\ConnectionPool->fetch()
#3 /mnt/c/users/twomiao/desktop/luckysheet-phpserver/vendor/workerman/http-client/src/Client.php(95): Workerman\Http\Client->process()
#4 /mnt/c/users/twomiao/desktop/luckysheet-phpserver/app/command/TestCase.php(44): Workerman\Http\Client->get()
#5 /mnt/c/users/twomiao/desktop/luckysheet-phpserver/vendor/symfony/console/Command/Command.php(298): app\command\TestCase->execute()
#6 in /mnt/c/users/twomiao/desktop/luckysheet-phpserver/vendor/workerman/workerman/Connection/AsyncTcpConnection.php on line 213`

### add() on null，这样提示似乎不太友好
判断如果是null，说明不在workerman 运行环境，throw new Exception("不在workerman 运行环境");

**Comment by walkor** [comment]
感谢反馈，如果可以的话请发pr吧，提示用英文提示
