### ISSUE TITLE
1.4.0后路由中 \w+ 无法解析带 // 文本

### ISSUE THREAD

**Issue by wolf-leo** [walkor/webman#336]
`
Route::get('/go/{url}', function($request, $url) {
    var_dump($url);
});
`

Example：
`http://127.0.0.1:8787/go/https%3A%2F%2Fwww.baidu.com`
或者
`http://127.0.0.1:8787/go/https://www.baidu.com`

无法识别

1.4.0 之前正常

**Comment by walkor** [comment]
主干已经修复，等下个版本一起发布
