### ISSUE TITLE
How to add SSL cert for HTTPS support ?

### ISSUE THREAD

**Issue by haidarvm** [walkor/webman#34]
For workerman it's easy, but how about webman?

**Comment by walkor** [comment]
Change config in `config/server.php` like this.
return [
    ....
    'transport'  => 'ssl', 
    'context'     => [ 
        'ssl' => array(
        'local_cert'                 => '/your.path/of/server.pem', 
        'local_pk'                   => '/your.path/of/server.key',
        'verify_peer'                => false,
    )],   
     ....
];

**Comment by haidarvm** [comment]
Fatal error: Uncaught Exception: class \Protocols\Https not exist in /root/Downloads/man/vendor/workerman/workerman/Worker.php:2303

sorry I could change it to 
```
'listen'               => 'http://0.0.0.0:443',
    'transport'            => 'tcp',
    'context'              => [ 
        'ssl' => array(
        'local_cert'   => '/root/certs/public.crt', 
        'local_pk'     => '/root/certs/private.key',
        'verify_peer'  => false,
    )],
```
but still when i try to change 'listen' to https it's error

```
Fatal error: Uncaught Exception: class \Protocols\Https not exist in /root/Downloads/man/vendor/workerman/workerman/Worker.php:2303
```
it's only work when I open in browser ```http://haidarvm.site:443```

so how can we use https ?

**Comment by haidarvm** [comment]
Sorry the problem is, It Cannot redirect to https when user just type my site ```haidarvm.ste``` example ? 
So how to auto redirect it to https ?

**Comment by walkor** [comment]
Add file `process/Redirect.php`.
```php
<?php
namespace process;

use Workerman\Connection\TcpConnection;
use Workerman\Protocols\Http\Request;

class Redirect
{
    public function onMessage(TcpConnection $connection, Request $request)
    {
        $url = $request->host(true) . $request->uri();
        $connection->send(redirect("https://$url"));
    }
}
```

Change `config/process.php` like this.
```php
<?php
return [
    'monitor' => [
        'handler'     => process\FileMonitor::class,
        'reloadable'  => false,
        'constructor' => [
            'monitor_dir' => [
                app_path(),
                config_path(),
                base_path() . '/process',
                base_path() . '/support',
                base_path() . '/resource'
            ],
            'monitor_extenstions' => [
                'php', 'html', 'htm'
            ]
        ]
    ],
    // Here the key.
    'redirect' => [
        'handler' => process\Redirect::class,
        'listen'  => 'http://0.0.0.0:80',
    ]
];
```

Restart webman with command `php start.php restart` or `php start.php restart -d`.

**Comment by haidarvm** [comment]
It's Works great

**Comment by haidarvm** [comment]
> Add file `process/Redirect.php`.
> 
> ```
> <?php
> namespace process;
> 
> use Workerman\Connection\TcpConnection;
> use Workerman\Protocols\Http\Request;
> 
> class Redirect
> {
>     public function onMessage(TcpConnection $connection, Request $request)
>     {
>         $url = $request->host(true) . $request->uri();
>         $connection->send(redirect("https://$url"));
>     }
> }
> ```
> 
> Change `config/process.php` like this.
> 
> ```
> <?php
> return [
>     'monitor' => [
>         'handler'     => process\FileMonitor::class,
>         'reloadable'  => false,
>         'constructor' => [
>             'monitor_dir' => [
>                 app_path(),
>                 config_path(),
>                 base_path() . '/process',
>                 base_path() . '/support',
>                 base_path() . '/resource'
>             ],
>             'monitor_extenstions' => [
>                 'php', 'html', 'htm'
>             ]
>         ]
>     ],
>     // Here the key.
>     'redirect' => [
>         'handler' => process\Redirect::class,
>         'listen'  => 'http://0.0.0.0:80',
>     ]
> ];
> ```
> 
> Restart webman with command `php start.php restart` or `php start.php restart -d`.

is it still works ?
there's no 
`config/process.php`
