### ISSUE TITLE
两个接口，在一个接口设置的session,在另一个接口拿不到数据

### ISSUE THREAD

**Issue by lozhu** [walkor/webman#346]
登陆之后设置$request->session()->set('user',$user),然后在获取用户信息接口里通过$request->session()->get('user')获取不到数据。。。代码基本上和webman-admin端的差不多，然后复制到app/controller下了，代码不报错。就是获取不到session

**Comment by walkor** [comment]
session依赖cookie，如果客户端不支持cookie或者客户端没有正确传递cookie给webman，那么session将失效。
另外如果使用了nginx代理，并且nginx代理proxy_cookie_path设置了secure;，那么只有https才能正确使用cookie，http无法使用cookie，也会导致session失效。
