### ISSUE TITLE
How to add Gzip encoding in header ?

### ISSUE THREAD

**Issue by haidarvm** [walkor/webman#35]
Usually add 
```header('Content-Encoding: gzip');``` in native php

But I did modify in core or add in return still not working 
```return new Response(200, ['Content-Encoding' => 'gzip'], "Hello World");```

And show error on browser
```Content Encoding Error```

Please we need Gzip Encoding for better compression and faster response

**Comment by walkor** [comment]
Try
```
return new Response(200, ['Content-Encoding' => 'gzip'], gzencode("Hello World"));
```

**Comment by haidarvm** [comment]
Ok thats work but how to override globally? So no need to add gzencode everytime ?

**Comment by walkor** [comment]
You can add a function for example.
```
function gzip($content) {
    return new Response(200, ['Content-Encoding' => 'gzip'], gzencode($content));
}
```
Then if you want to use gzip as response just call it.

**Comment by walkor** [comment]
Another way. `support/Response.php` is an empty file to override default behavior of `Response`. Change `support/Response.php` like this.
```php
<?php
namespace support;
class Response extends \Webman\Http\Response
{
    public function __construct($status = 200, array $headers = array(), $body = '')
    {
        $headers += ['Content-Encoding' => 'gzip'];
        $body = gzencode($body);
        parent::__construct($status, $headers, $body);
    }

    public function withBody($body)
    {
        $body = gzencode($body);
        return parent::withBody($body);
    }
}
```

Then call
```php
return response('hello world');
 // or
return new Response(200, [], "Hello World");
```
Gzip will be used as globally.
