### ISSUE TITLE
Need Help Getting Browser-Detect or Mobile-Detect to Work with Webman

### ISSUE THREAD

**Issue by DLLDev** [walkor/webman#377]
Hey Walkor,

I'm working with Webman and I've been trying to figure out how to get some browser detection happening. Specifically, I've been looking at [browser-detect](https://github.com/hisorange/browser-detect) or as alternative [Mobile-Detect](https://github.com/serbanghita/Mobile-Detect), but I can't seem to get either of them integrated properly.

It's pretty important to me to know what type of device and browser my users are using so I can make sure everything looks and works great for them. I would prefer to get "browser-detect" running if possible, as it have more features then Mobile-Detect.

Is there any way to get these libraries running in Webman that I might have missed?

Any advice or help would be highly appreciated.

Cheers!

DLLDev

**Comment by Chance-fyi** [comment]
You can use it like this.

```php
public function index(Request $request)
{
    $agent = $request->header('user-agent');
    $result = (new \hisorange\BrowserDetect\Parser())->parse($agent);

    return json($result->toArray());
}
```

**Comment by DLLDev** [comment]
Works perfectly, thanks!
