### ISSUE TITLE
变量名称错误导致控制台打印状态报错

### ISSUE THREAD

**Issue by forever2077** [walkor/webman#381]
webman版本：v1.5.8
一个变量名称错误导致控制台打印状态报错
![微信截图_20230731132831](https://github.com/walkor/webman/assets/133069414/17639ffa-ed4e-4c7b-a1e4-e48040d0e607)
![微信截图_20230731132912](https://github.com/walkor/webman/assets/133069414/aa669eae-cb0a-43e6-be01-4047f0cd088d)

**Comment by walkor** [comment]
Fixed

**Comment by walkor** [comment]
composer require workerman/workerman ^4.1.13
