### ISSUE TITLE
压测在webman中进行 redis  get  效果不是很理想, 原因未知.. 

### ISSUE THREAD

**Issue by zwfec** [walkor/webman#385]
> 请求了8次说法应该不准确，应该是只建立了8个redis连接。
> webman里redis单例就是为了复用redis连接，每个进程只需要实例化连接一次。如果你是8个进程，就实例化8次。并不是8000并发就实例化8000次。
```bash
php start.php start    
Workerman[start.php] start in DEBUG mode
-------------------------------------------- WORKERMAN --------------------------------------------
Workerman version:4.1.13          PHP version:8.1.22           Event-Loop:\Workerman\Events\Select
--------------------------------------------- WORKERS ---------------------------------------------
proto   user            worker          listen                 processes    status           
tcp     app        webman          http://0.0.0.0:8787    8             [OK]   

```

测试了下在相同环境时单纯原生 php 连接 redis 比在webman中快,
比如最简单这句: 
```php
    for ($i = 1; $i < 200; $i++) {
            \support\Redis::get('xxxx');
    }
    return 'ok';
````

### **添加 redis get 200次的循环代码块 :** 
ab -c100 -n1000 http://127.0.0.1:8787/testredis/

结果:
Concurrency Level:      100
Time taken for tests:   63.801 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      122000 bytes
HTML transferred:       2000 bytes
**Requests per second:    15.67 [#/sec] (mean)**
Time per request:       6380.051 [ms] (mean)
Time per request:       63.801 [ms] (mean, across all concurrent requests)
Transfer rate:          1.87 [Kbytes/sec] received

### **去除 redis get 200次的循环代码块 :** 
ab -c100 -n1000 http://127.0.0.1:8787/testredis/

Concurrency Level:      100
Time taken for tests:   0.074 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      122000 bytes
HTML transferred:       2000 bytes
**Requests per second:    13478.54 [#/sec] (mean)**
Time per request:       7.419 [ms] (mean)
Time per request:       0.074 [ms] (mean, across all concurrent requests)
Transfer rate:          1605.84 [Kbytes/sec] received

**怎么能相差这么多, 理论上redis  get 应该很快吧,  
源码里查了一下可能的原因, 也没查到, 不清楚是哪里影响到了..**

**Comment by jeckleee** [comment]
我刚刚使用本地redis服务试了一下: 

//代码
for ($i = 1; $i < 200; $i++) {
    Redis::get('aa');
}
return response('ok');

//8进程压测
Concurrency Level:      100
Time taken for tests:   8.637 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      122000 bytes
HTML transferred:       2000 bytes
Requests per second:    115.78 [#/sec] (mean)
Time per request:       863.724 [ms] (mean)
Time per request:       8.637 [ms] (mean, across all concurrent requests)
Transfer rate:          13.79 [Kbytes/sec] received

我这个是本地redis,你要不是本地redis,成绩肯定会更差

**Comment by zwfec** [comment]
> 我刚刚使用本地redis服务试了一下:
> 
> //代码 for ($i = 1; $i < 200; $i++) { Redis::get('aa'); } return response('ok');
> 
> //8进程压测 Concurrency Level: 100 Time taken for tests: 8.637 seconds Complete requests: 1000 Failed requests: 0 Total transferred: 122000 bytes HTML transferred: 2000 bytes Requests per second: 115.78 [#/sec] (mean) Time per request: 863.724 [ms] (mean) Time per request: 8.637 [ms] (mean, across all concurrent requests) Transfer rate: 13.79 [Kbytes/sec] received
> 
> 我这个是本地redis,你要不是本地redis,成绩肯定会更差.

是的, 这个测试是 mac 下 docker 里的 redis server 

测试过当前机器的redis server, 基本可以到 Requests per second: 220+ [#/sec] (mean)

**Comment by walkor** [comment]
Redis很快，但是也有极限，普通服务器的Redis的QPS最高就大概10万QPS左右。
每个请求200次redis访问，10W/200 = 500QPS，所以这种200次Redis访问的业务任何语言、任何框架压测出来结果都是几百，没什么好聊的。

还有压测上正常linux服务器，不要用docker或虚拟机。压测记得加-k，否则很容易本地端口用光导致延迟影响结果。
这种巨慢的业务压测最好把 config/server.php里的reuse_port打开，让连接均摊到每个进程。

以下是4核4G腾讯轻量服务器压测结果
**webman的**
![image](https://github.com/walkor/webman/assets/6073368/83510fc3-a635-4006-a96f-8e771d2aedf1)

**php-fpm的**
![image](https://github.com/walkor/webman/assets/6073368/078775a7-66b0-4c3a-b28e-20a2b10e57fe)

**Comment by zwfec** [comment]
> Redis很快，但是也有极限，普通服务器的Redis的QPS最高就大概10万QPS左右。 每个请求200次redis访问，10W/200 = 500QPS，所以这种200次Redis访问的业务任何语言、任何框架压测出来结果都是几百，没什么好聊的。
> 
> 还有压测上正常linux服务器，不要用docker或虚拟机。压测记得加-k，否则很容易本地端口用光导致延迟影响结果。 这种巨慢的业务压测最好把 config/server.php里的reuse_port打开，让连接均摊到每个进程。
> 

明白了, 谢谢!
使用 golang 压了一下, mac 下没有相关配置优化的情况下,  效果也差不多: 

<img width="613" alt="image" src="https://github.com/walkor/webman/assets/1873117/2d59abc9-febe-4e6c-a068-c511ccfe924b">
