### ISSUE TITLE
建议作者大大将webman容器类，构造控制器的时候，考虑控制器有参数的情况

### ISSUE THREAD

**Issue by avriltank** [walkor/webman#39]
假如Index控制器，如下：
   public function __construct($name)
   {
       $this->name = $name;
       
   }
webman App类在分发路由的时候代码如下：
                $app = $controller_and_action['app'];
                $controller = $controller_and_action['controller'];
                $action = $controller_and_action['action'];
                $callback = static::getCallback($app, [static::$_container->get($controller), $action]);
//建议这里通过反射处理下controller构造函数有参数的情况
                static::$_callbacks[$key] = [$callback, $app, $controller, $action];
                list($callback, $request->app, $request->controller, $request->action) = static::$_callbacks[$key];
                static::send($connection, $callback($request), $request);
![图片](https://user-images.githubusercontent.com/13652682/93885405-aeae7c80-fd16-11ea-8c3d-fc398e55fdb4.png)

webman中自带Container类的get方法代码如下，没考虑控制器构造函数有参数的情况：
    public function get($name)//构造函数无参数情况
    {
        if (!isset($this->_instances[$name])) {
            if (!class_exists($name)) {
                throw new NotFoundException("Class '$name' not found");
            }
            $this->_instances[$name] = new $name();
        }
        return $this->_instances[$name];
    }
所以会报错，个人建议作者大大，可以考虑把这种虽然比较少用的情况也考虑优化进去
![图片](https://user-images.githubusercontent.com/13652682/93885004-30ea7100-fd16-11ea-8258-55e1309436c7.png)

**Comment by walkor** [comment]
webman里控制器应该是单例的，并且各个请求可以复用，同一个控制器不应该出现多个实例。如果控制器构造函数有参数，就无法确认实例化的时候传递什么参数。比如说`$this->name`，框架启动的时候应该传递什么参数给`$this->name`实例化呢？

**Comment by avriltank** [comment]
谢谢回复，如果是单例的话，那按照webman文档https://www.workerman.net/doc/webman#/di，用php-di的情况，就感觉没必要了。

**Comment by walkor** [comment]
控制器是单例，其它业务创建的类没有限制必须单例，如果你想用容器初始化带参数的类，可以用`\support\bootstrap\Container::make(类名, [构造函数参数])`方法，但是这个方法与`\support\bootstrap\Container::get(类名)`不同，make返回的类不是单例，每次调用make都会重新初始化一个新的类出来，而get方法返回的是单例，不会每次重复初始化。

使用单例不影响使用php-di。php-di 主要是为了解决依赖自动注入包括注解注入，和框架使用单例没有什么冲突。

**Comment by avriltank** [comment]
好的，明白了。谢谢哈
