### ISSUE TITLE
support\Request不支持依赖注入

### ISSUE THREAD

**Issue by lanrenbulan** [walkor/webman#391]
cannot be resolved: Entry "support\Request" cannot be resolved: Parameter $buffer of __construct() has no value defined or guessable

**Comment by walkor** [comment]
support\Request不支持依赖注入，你可以使用request()方法来获取当前请求对象

**Comment by lanrenbulan** [comment]
> support\Request不支持依赖注入，你可以使用request()方法来获取当前请求对象

正是如此。
