### ISSUE TITLE
依赖注入，适配symfony的依赖组入组件吗？

### ISSUE THREAD

**Issue by lanrenbulan** [walkor/webman#392]
https://symfony.com/doc/current/components/dependency_injection.html

Error: Call to private method Symfony\Component\DependencyInjection\Container::make() from scope support\Container in /vendor/workerman/webman-framework/src/support/Container.php

**Comment by walkor** [comment]
没试过&nbsp;


walkor
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月18日(星期一) 晚上7:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [walkor/webman] 依赖注入，适配symfony的依赖组入组件吗？ (Issue #392)





 
https://symfony.com/doc/current/components/dependency_injection.html
 
Error: Call to private method Symfony\Component\DependencyInjection\Container::make() from scope support\Container in /vendor/workerman/webman-framework/src/support/Container.php
