### ISSUE TITLE
webman 使用php8.3.1, workerman v5 bate7 , 安装了swow扩展后读取配置文件一直报错

### ISSUE THREAD

**Issue by lly0414** [walkor/webman#396]
```php
UnexpectedValueException: RecursiveDirectoryIterator::__construct(/mnt/hgfs/test/webman/config/app.php): Failed to open directory: Not a directory in /mnt/hgfs/test/webman/vendor/workerman/webman-framework/src/Config.php:191
Stack trace:
#0 [internal function]: RecursiveDirectoryIterator->__construct()
#1 /mnt/hgfs/test/webman/vendor/workerman/webman-framework/src/Config.php(191): RecursiveDirectoryIterator->getChildren()
#2 /mnt/hgfs/test/webman/vendor/workerman/webman-framework/src/Config.php(63): Webman\Config::loadFromDir()
#3 /mnt/hgfs/test/webman/vendor/workerman/webman-framework/src/support/App.php(141): Webman\Config::load()
#4 /mnt/hgfs/test/webman/support/bootstrap.php(48): support\App::loadAllConfig()
#5 /mnt/hgfs/test/webman/vendor/workerman/webman-framework/src/support/App.php(104): require_once('...')
#6 /mnt/hgfs/test/webman/vendor/workerman/workerman/src/Worker.php(2443): support\App::support\{closure}()
#7 /mnt/hgfs/test/webman/vendor/workerman/workerman/src/Worker.php(1592): Workerman\Worker->run()
#8 /mnt/hgfs/test/webman/vendor/workerman/workerman/src/Worker.php(1394): Workerman\Worker::forkOneWorkerForLinux()
#9 /mnt/hgfs/test/webman/vendor/workerman/workerman/src/Worker.php(1368): Workerman\Worker::forkWorkersForLinux()
#10 /mnt/hgfs/test/webman/vendor/workerman/workerman/src/Worker.php(572): Workerman\Worker::forkWorkers()
#11 /mnt/hgfs/test/webman/vendor/workerman/webman-framework/src/support/App.php(131): Workerman\Worker::runAll()
#12 /mnt/hgfs/test/webman/start.php(4): support\App::run()
#13 {main}
```
卸载swow扩展,  或者把php版本撤回到8.2后都不会报错了

**Comment by walkor** [comment]
可能是swow影响了php的默认行为导致的
&nbsp;


walkor
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sophia ***@***.***&gt;; 
发送时间: 2024年1月17日(星期三) 下午4:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [walkor/webman] webman 使用php8.3.1, workerman v5 bate7 , 安装了swow扩展后读取配置文件一直报错 (Issue #396)





 UnexpectedValueException: RecursiveDirectoryIterator::__construct(/mnt/hgfs/test/webman/config/app.php): Failed to open directory: Not a directory in /mnt/hgfs/test/webman/vendor/workerman/webman-framework/src/Config.php:191 Stack trace: #0 [internal function]: RecursiveDirectoryIterator-&gt;__construct() #1 /mnt/hgfs/test/webman/vendor/workerman/webman-framework/src/Config.php(191): RecursiveDirectoryIterator-&gt;getChildren() #2 /mnt/hgfs/test/webman/vendor/workerman/webman-framework/src/Config.php(63): Webman\Config::loadFromDir() #3 /mnt/hgfs/test/webman/vendor/workerman/webman-framework/src/support/App.php(141): Webman\Config::load() #4 /mnt/hgfs/test/webman/support/bootstrap.php(48): support\App::loadAllConfig() #5 /mnt/hgfs/test/webman/vendor/workerman/webman-framework/src/support/App.php(104): require_once('...') #6 /mnt/hgfs/test/webman/vendor/workerman/workerman/src/Worker.php(2443): support\App::support\{closure}() #7 /mnt/hgfs/test/webman/vendor/workerman/workerman/src/Worker.php(1592): Workerman\Worker-&gt;run() #8 /mnt/hgfs/test/webman/vendor/workerman/workerman/src/Worker.php(1394): Workerman\Worker::forkOneWorkerForLinux() #9 /mnt/hgfs/test/webman/vendor/workerman/workerman/src/Worker.php(1368): Workerman\Worker::forkWorkersForLinux() #10 /mnt/hgfs/test/webman/vendor/workerman/workerman/src/Worker.php(572): Workerman\Worker::forkWorkers() #11 /mnt/hgfs/test/webman/vendor/workerman/webman-framework/src/support/App.php(131): Workerman\Worker::runAll() #12 /mnt/hgfs/test/webman/start.php(4): support\App::run() #13 {main}

**Comment by lly0414** [comment]
好的 我去swow库那问一下
