### ISSUE TITLE
关于 Timer::add  的bug

### ISSUE THREAD

**Issue by jackbon8** [walkor/webman#397]
![76TUJZODQ722P@`J F({V1S](https://github.com/walkor/webman/assets/43921493/eacef126-4ce8-4dac-bc52-91de2b6afac4)
上面图片是逻辑``示例``
真实情况是 接收到用户特定的数据 开启定时任务 是有条件限制的
链接用户多的情况下  出现了    redis队列数据混读的情况

**Comment by walkor** [comment]
按照workerman文档，数据库 redis等不能直接在start.php里初始化，建议放在onWorkerStart里初始化。
另外你这个issue发错地方了，这个是webman项目。
