### ISSUE TITLE
[bug] $request->action在控制器中不存在方法时该值始终返回小写

### ISSUE THREAD

**Issue by wolf-leo** [walkor/webman#399]
场景如下 
正常控制器写法
![image](https://github.com/walkor/webman/assets/37436228/4005cab9-445f-4a9c-839f-70d7270b5732)

这时候请求该接口，我在统一中间件中获取 $request->action ，得到 getUserInfo

目前为止正常

下面开始异常
![image](https://github.com/walkor/webman/assets/37436228/beffec9a-afbc-4837-9645-fd82156531d4)

用PHP的魔术方法去调用 getUserInfo ，这时候中间件的  $request->action 返回 getuserinfo

到这里的时候逻辑开始出错了...

**Comment by walkor** [comment]
如果控制器使用了__call魔术方法，$function_name的值就是具体的action，$function_name是getUserInfo则action就是getUserInfo，是getuserinfo则action就是getuserinfo，没有问题。

**Comment by wolf-leo** [comment]
> 如果控制器使用了__call魔术方法，$function_name的值就是具体的action，$function_name是getUserInfo则action就是getUserInfo，是getuserinfo则action就是getuserinfo，没有问题。

现在访问的 Test/getUserInfo，_call() 调用  , ->action 返回的是小写的 getuserinfo

**Comment by walkor** [comment]
下个版本兼容下

**Comment by yisibugua** [comment]
自己转换一下吧...
然后，讨厌写_call魔术方法
