### ISSUE TITLE
期望

### ISSUE THREAD

**Issue by zoujingli** [walkor/webman#4]
希望框架可以同时支持 php-fpm  及 WorkerServer。
目前大部分环境依然是 ng|ap，也有需要 php 能独立完成 web整套服务的框架。
当前我也有这种需要，基于Workerman+ThinkPHP v6也有做一套应用，但总体不太理想，原因是TP有些地方在Command运行时问题很多，不方便进行二次调整！希望 webman可以在这方面做得更好。
如果 webman 可以二者运行模式兼备，相信框架发展会更好！！！

**Comment by walkor** [comment]
在线主要精力放在开发基于workerman的框架，基于php-fpm的没有最终确认是否开发，到时候看需求情况。

**Comment by zoujingli** [comment]
好的，期待。。。
加油！！！
