### ISSUE TITLE
400 bad request on post with body

### ISSUE THREAD

**Issue by vying1** [walkor/webman#40]
Steps to recreate error:

Create a get route
Create a post route

Send a body of {"test": "test"} as application/json

Start server and run get requests -> 200 OK
Quit server, start again and run post requests -> 200 OK

Start server and run get request -> 200 OK
Run post request -> 400 bad request
Run post request again -> 200 OK on all subsequent requests

Does not occur with an empty body on post.  

Thanks.

**Comment by walkor** [comment]
Webman does not support `GET` requests with body. Please check that.

**Comment by vying1** [comment]
Yes that's it, it only comes up if the preceding GET has a body.  Thank you.
