### ISSUE TITLE
Redis Prefix caused multiple deletion failed

### ISSUE THREAD

**Issue by jyxjjj** [walkor/webman#405]
Redis::set and Redis::del will add prefix, but Redis::keys will return keys with the prefix, we must have to map the results to remove the prefix then we can now delete multiple keys by one command.

Such as : 
```
Redis::set("abc",1);
// prefix_abc
Redis::keys("abc");
// [prefix_abc]
Redis::del($keys);
// delete prefix_prefix_abc failed due to not exists
```

Must : 
```
map($keys, fn()=>str_replace(prefix))
```

**Comment by jyxjjj** [comment]
![image](https://github.com/walkor/webman/assets/16695261/ad88f273-93c7-40e0-be83-d6f2ef0beb3b)
![image](https://github.com/walkor/webman/assets/16695261/37cc3657-cc5b-4382-924a-5892993534f2)

**Comment by walkor** [comment]
Redis is using the [illuminate/redis](https://github.com/illuminate/redis) library, which is not under our control. They might have their own considerations for using it. If you believe there is an issue with the library, you can contact them directly.
