### ISSUE TITLE
模型注释 查询语句加where  IDE没有依赖注入

### ISSUE THREAD

**Issue by YouZiXiL** [walkor/webman#408]
![image](https://github.com/walkor/webman/assets/48539892/de54169b-5519-471c-877d-8487d0444eb4)

**Comment by YouZiXiL** [comment]
模型注释 查询语句加where  IDE没有依赖注入

**Comment by YouZiXiL** [comment]
Webman-framework v1.5.16

**Comment by walkor** [comment]
数据库组件是laravel控制的项目，不是webman控制的。
应该是加上where后返回的类型是不可预知的，你可以强制加加一个类型标记给它。

```
/* @var Users $row */
$row = Users::where( column: "id'operator: 1)->first();
```

**Comment by YouZiXiL** [comment]
最新版已优化
