### ISSUE TITLE
php8.1环境安装 ORM 后报错

### ISSUE THREAD

**Issue by keanu-jinu** [walkor/webman#417]
PHP8.1 环境

composer require "illuminate/events"

但是Sympony/clock/composer.json 要求
"php": ">=8.2"

进而无法运行项目了
PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0". You are running 8.1.29.

**Comment by walkor** [comment]
贴下项目根目录composer.json

**Comment by keanu-jinu** [comment]
> 贴下项目根目录composer.json

{
  "name": "workerman/webman",
  "type": "project",
  "keywords": [
    "high performance",
    "http service"
  ],
  "homepage": "https://www.workerman.net",
  "license": "MIT",
  "description": "High performance HTTP Service Framework.",
  "authors": [
    {
      "name": "walkor",
      "email": "walkor@workerman.net",
      "homepage": "https://www.workerman.net",
      "role": "Developer"
    }
  ],
  "support": {
    "email": "walkor@workerman.net",
    "issues": "https://github.com/walkor/webman/issues",
    "forum": "https://wenda.workerman.net/",
    "wiki": "https://workerman.net/doc/webman",
    "source": "https://github.com/walkor/webman"
  },
  "require": {
    "php": ">=7.2",
    "workerman/webman-framework": "^1.5.0",
    "monolog/monolog": "^2.0"
  },
  "suggest": {
    "ext-event": "For better performance. "
  },
  "autoload": {
    "psr-4": {
      "": "./",
      "app\\": "./app",
      "App\\": "./app",
      "app\\View\\Components\\": "./app/view/components"
    },
    "files": [
      "./support/helpers.php"
    ]
  },
  "scripts": {
    "post-package-install": [
      "support\\Plugin::install"
    ],
    "post-package-update": [
      "support\\Plugin::install"
    ],
    "pre-package-uninstall": [
      "support\\Plugin::uninstall"
    ]
  },
  "minimum-stability": "dev",
  "prefer-stable": true
}

**Comment by walkor** [comment]
你看下你项目是不是从8.2.0的php环境拷贝到了php 8.1来的。因为你本地是8.1，所以8.2的vendor里的库跑不起来提示这个错误。
如果项目拷贝到其它服务器，需要保证php版本是一样的。
或者你把vendor和composer.lock删除重新运行 composer install

**Comment by keanu-jinu** [comment]
> 你看下你项目是不是从8.2.0的php环境拷贝到了php 8.1来的。因为你本地是8.1，所以8.2的vendor里的库跑不起来提示这个错误。 如果项目拷贝到其它服务器，需要保证php版本是一样的。 或者你把vendor和composer.lock删除重新运行 composer install

我现在拆卸 PHP，然后重装到 8.1 然后再试一下

**Comment by walkor** [comment]
重装8.1没用。你的vendor还是php 8.2的，删除 vendor和composer.lock 重新运行  composer install 就好了

**Comment by keanu-jinu** [comment]
> 重装8.1没用。你的vendor还是php 8.2的，删除 vendor和composer.lock 重新运行 composer install 就好了

我表述有问题，我的意思是，拆卸 php8.1 创建空项目，然后根据 redis 和数据库章节的教程重新做一遍。感谢大佬

**Comment by walkor** [comment]
翻译过来意思是你composer.json 里设置的 illuminate/database 版本是^11.25，需要php8.2才能运行。
把composer.json 后面装的组件从composer删除重新装吧。

**Comment by keanu-jinu** [comment]
感谢，已经清理了 PHP 环境，新建项目处理了
