### ISSUE TITLE
session 如何配置分布式redis

### ISSUE THREAD

**Issue by dhw-daniel** [walkor/webman#42]

**Comment by dhw-daniel** [comment]
RedisException: MOVED 3934 192.168.7.230:6379 in /data/wwwroot/webman/vendor/workerman/workerman/Protocols/Http/Session/RedisSessionHandler.php:84
Stack trace:

**Comment by walkor** [comment]
新建 support/RedisClusterSessionHandler.php
```php
<?php
namespace support;
use Workerman\Protocols\Http\Session\RedisSessionHandler;

class RedisClusterSessionHandler extends RedisSessionHandler
{
    protected $_maxLifeTime = 1440;

    public function __construct($config)
    {
        $this->_redis = new \RedisCluster(null, ...array_values($config));
    }
}
```
更改配置 config/session.php
```php
return [

    'type'    => 'redis_cluster', // <==注意这里

    'handler' => support\RedisClusterSessionHandler::class,  // <==注意这里

    'config' => [
        'file' => [
            'save_path' => runtime_path() . '/sessions',
        ],
        'redis' => [
            'host'      => '127.0.0.1',
            'port'      => 6379,
            'auth'      => '',
            'timeout'   => 2,
            'database'  => '',
            'prefix'    => 'redis_session_',
        ],
        'redis_cluster' => [  // <==注意这里
            'host'         => ['host1:6379', 'host2:6379', ....],
            'timeout'      => 2,
            'read_timeout' => 2,
            'persistent'   => true,
        ]
    ],

    'session_name' => 'PHPSID',
];
```

**Comment by dhw-daniel** [comment]
感谢大佬，我刚刚是新建文件使用了 Illuminate\Redis\RedisManager的redis连接也解决了，能在官方文档上表现分布式redis连接方案就好了我新建support/RedisClusterSessionHandler.php文件的代码为这样
`<?php

namespace support;

use Illuminate\Redis\RedisManager;

/**
 * Class Session
 * @package support
 */
class RedisClusterSessionHandler extends \SessionHandler {

    /**
     * @var \Redis
     */
    protected $_redis;

    /**
     * @var int
     */
    protected $_maxLifeTime;


    public function __construct($config)
    {
        if (!class_exists('\Illuminate\Redis\RedisManager')) {
            return;
        }
        $this->_maxLifeTime = (int)ini_get('session.gc_maxlifetime');

        $redis_config = config('redis');

        $this->_redis =  new RedisManager('', 'phpredis', $redis_config);
        if (!isset($config['timeout'])) {
            $config['timeout'] = 2;
        }
        if (!empty($config['auth'])) {
            $this->_redis->auth($config['auth']);
        }
        if (!empty($config['database'])) {
            $this->_redis->select($config['database']);
        }
        if (empty($config['prefix'])) {
            $config['prefix'] = 'redis_session_';
        }
        $this->_redis->setOption(\Redis::OPT_PREFIX, $config['prefix']);
    }

    /**
     * {@inheritdoc}
     */
    public function open($save_path, $name)
    {
        return true;
    }

    /**
     * {@inheritdoc}
     */
    public function read($session_id)
    {
        return $this->_redis->get($session_id);
    }

    /**
     * {@inheritdoc}
     */
    public function write($session_id, $session_data)
    {
        return true === $this->_redis->setex($session_id, $this->_maxLifeTime, $session_data);
    }

    /**
     * {@inheritdoc}
     */
    public function destroy($session_id)
    {
        $this->_redis->del($session_id);
        return true;
    }

    /**
     * {@inheritdoc}
     */
    public function close()
    {
        return true;
    }

    /**
     * {@inheritdoc}
     */
    public function gc($maxlifetime)
    {
        return true;
    }
}`

**Comment by dhw-daniel** [comment]
感谢大佬，我刚刚是新建文件使用了 Illuminate\Redis\RedisManager的redis连接也解决了，能在官方文档上表现分布式redis连接方案就好了我新建support/RedisClusterSessionHandler.php文件的代码为这样

`<?php
namespace support;

use Illuminate\Redis\RedisManager;

class RedisClusterSessionHandler extends \SessionHandler {

    protected $_redis;
    protected $_maxLifeTime;

    public function __construct($config)
    {
        if (!class_exists('\Illuminate\Redis\RedisManager')) {
            return;
        }
        $this->_maxLifeTime = (int)ini_get('session.gc_maxlifetime');

        $redis_config = config('redis');

        $this->_redis =  new RedisManager('', 'phpredis', $redis_config);
        if (!isset($config['timeout'])) {
            $config['timeout'] = 2;
        }
        if (!empty($config['auth'])) {
            $this->_redis->auth($config['auth']);
        }
        if (!empty($config['database'])) {
            $this->_redis->select($config['database']);
        }
        if (empty($config['prefix'])) {
            $config['prefix'] = 'redis_session_';
        }
        $this->_redis->setOption(\Redis::OPT_PREFIX, $config['prefix']);
    }

    public function open($save_path, $name)
    {
        return true;
    }

    public function read($session_id)
    {
        return $this->_redis->get($session_id);
    }

    public function write($session_id, $session_data)
    {
        return true === $this->_redis->setex($session_id, $this->_maxLifeTime, $session_data);
    }

    public function destroy($session_id)
    {
        $this->_redis->del($session_id);
        return true;
    }

    public function close()
    {
        return true;
    }

    public function gc($maxlifetime)
    {
        return true;
    }
}`

**Comment by dhw-daniel** [comment]
感谢

**Comment by walkor** [comment]
![image](https://user-images.githubusercontent.com/6073368/94226801-14735200-ff2b-11ea-87a7-24011d8616e6.png)

https://www.workerman.net/doc/webman#/session
已加。
如果看不到最新的文档尝试清理下浏览器缓存。

**Comment by dhw-daniel** [comment]
大佬，我composer update后
新建 support/RedisClusterSessionHandler.php
`
<?php
namespace support;
use Workerman\Protocols\Http\Session\RedisSessionHandler;

class RedisClusterSessionHandler extends RedisSessionHandler
{
    protected $_maxLifeTime = 1440;

    public function __construct($config)
    {
        $this->_redis = new \RedisCluster(null, ...array_values($config));
    }
}
`
更改配置 config/session.php
`
<?php
return [
    /*
    'type'    => env('SESSION_DRIVER', 'file'), // or redis or redis_cluster
    'handler' => Webman\FileSessionHandler::class,
    */
    /*
    'type'    => env('SESSION_DRIVER', 'redis'), // or redis or redis_cluster
    'handler' => support\RedisClusterSession::class,
    */

    'type'    => env('SESSION_DRIVER', 'redis_cluster'),
    'handler' => support\RedisClusterSessionHandler::class,

    'config' => [
        'file' => [
            'save_path' => runtime_path() . '/sessions',
        ],
        'redis' => [
            'host'      => env('REDIS_HOST_REB1',''),
            'port'      => env('REDIS_PORT', '6379'),
            'auth'      => '',
            'timeout'   => 2,
            'database'  => '0',
            'prefix'    => 'php:session:webman:',
        ],
        'redis_cluster' => [
            'host'    => [
                0 => env('REDIS_HOST_REB0', 'localhost').':'.env('REDIS_PORT', 6379),
                1 => env('REDIS_HOST_REB1', 'localhost').':'.env('REDIS_PORT', 6379),
                2 => env('REDIS_HOST_REB2', 'localhost').':'.env('REDIS_PORT', 6379),
                3 => env('REDIS_HOST_REB3', 'localhost').':'.env('REDIS_PORT', 6379),
                4 => env('REDIS_HOST_REB4', 'localhost').':'.env('REDIS_PORT', 6379),
                5 => env('REDIS_HOST_REB5', 'localhost').':'.env('REDIS_PORT', 6379),
            ],
            'password' => env('REDIS_PASSWORD', null),
            'timeout' => 2,
            'read_timeout' => 2,
            'auth'    => '',
            'persistent'   => true,
            'prefix'    => 'php:session:webman11:',
        ]
    ],

    'session_name' => 'PHPSID',
];
`

页面提示错误信息
RedisClusterException: The slot 8589 is not covered by any node in this cluster in /data/wwwroot/webman/vendor/workerman/workerman/Protocols/Http/Session/RedisSessionHandler.php:84
Stack trace:
#0 /data/wwwroot/webman/vendor/workerman/workerman/Protocols/Http/Session/RedisSessionHandler.php(84): RedisCluster->get('fe0b46f451dbd74...')
#1 /data/wwwroot/webman/vendor/workerman/workerman/Protocols/Http/Session.php(98): Workerman\Protocols\Http\Session\RedisSessionHandler->read('fe0b46f451dbd74...')
#2 /data/wwwroot/webman/vendor/workerman/workerman/Protocols/Http/Request.php(283): Workerman\Protocols\Http\Session->__construct('fe0b46f451dbd74...')
#3 /data/wwwroot/webman/app/controller/Index.php(13): Workerman\Protocols\Http\Request->session()
#4 /data/wwwroot/webman/vendor/workerman/webman-framework/src/App.php(168): app\controller\Index->index(Object(support\Request))
#5 /data/wwwroot/webman/vendor/workerman/workerman/Connection/TcpConnection.php(660): Webman\App->onMessage(Object(Workerman\Connection\TcpConnection), Object(support\Request))
#6 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #187, 2, Resource id #187)
#7 /data/wwwroot/webman/vendor/workerman/workerman/Events/Event.php(195): EventBase->loop()
#8 /data/wwwroot/webman/vendor/workerman/workerman/Worker.php(2417): Workerman\Events\Event->loop()
#9 /data/wwwroot/webman/vendor/workerman/workerman/Worker.php(1542): Workerman\Worker->run()
#10 /data/wwwroot/webman/vendor/workerman/workerman/Worker.php(1372): Workerman\Worker::forkOneWorkerForLinux(Object(Workerman\Worker))
#11 /data/wwwroot/webman/vendor/workerman/workerman/Worker.php(1346): Workerman\Worker::forkWorkersForLinux()
#12 /data/wwwroot/webman/vendor/workerman/workerman/Worker.php(542): Workerman\Worker::forkWorkers()
#13 /data/wwwroot/webman/start.php(138): Workerman\Worker::runAll()
#14 {main}

控制台提示信息

Warning: RedisCluster::__construct() expects at most 6 parameters, 8 given in /data/wwwroot/webman/support/RedisClusterSessionHandler.php on line 11

**Comment by walkor** [comment]
按照手册来，用 `'handler' => Webman\RedisClusterSessionHandler::class,`。
配置项只有三个
```
'redis_cluster' => [
            'host'    => ['127.0.0.1:7000', '127.0.0.1:7001', '127.0.0.1:7001'],
            'timeout' => 2,
            'auth'    => '',
        ]
```

**Comment by dhw-daniel** [comment]
配置项我改为3个依然出现同样的问题

**Comment by dhw-daniel** [comment]
不好意思我引用成之前自己创建的support/RedisClusterSessionHandler.php了，改为'handler' => Webman\RedisClusterSessionHandler::class  后配置6个也没有问题

**Comment by dhw-daniel** [comment]
还有个问题，键的前缀怎么设置呢

**Comment by walkor** [comment]
更新webman-framework 到1.0.5或者后续更高版本。
用prefix来设置前缀，类似这样
```php
'redis_cluster' => [
            'host'    => ['127.0.0.1:7000', '127.0.0.1:7001', '127.0.0.1:7001'],
            'timeout' => 2,
            'auth'    => '',
            'prefix'  => 'redis_session_',
        ]
```

**Comment by dhw-daniel** [comment]
composer update 并添加prefix后上报错了

```
RedisClusterException: Couldn't map cluster keyspace using any provided seed in /data/wwwroot/webman/vendor/workerman/webman-framework/src/RedisClusterSessionHandler.php:30
Stack trace:
#0 /data/wwwroot/webman/vendor/workerman/webman-framework/src/RedisClusterSessionHandler.php(30): RedisCluster->__construct(NULL, Array, 2, 2, false)
#1 /data/wwwroot/webman/vendor/workerman/workerman/Protocols/Http/Session.php(308): Webman\RedisClusterSessionHandler->__construct(Array)
#2 /data/wwwroot/webman/vendor/workerman/workerman/Protocols/Http/Session.php(95): Workerman\Protocols\Http\Session::initHandler()
#3 /data/wwwroot/webman/vendor/workerman/workerman/Protocols/Http/Request.php(283): Workerman\Protocols\Http\Session->__construct('fe0b46f451dbd74...')
#4 /data/wwwroot/webman/app/controller/Index.php(13): Workerman\Protocols\Http\Request->session()
#5 /data/wwwroot/webman/vendor/workerman/webman-framework/src/App.php(140): app\controller\Index->index(Object(support\Request))
#6 /data/wwwroot/webman/vendor/workerman/workerman/Connection/TcpConnection.php(660): Webman\App->onMessage(Object(Workerman\Connection\TcpConnection), Object(support\Request))
#7 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #190, 2, Resource id #190)
#8 /data/wwwroot/webman/vendor/workerman/workerman/Events/Event.php(195): EventBase->loop()
#9 /data/wwwroot/webman/vendor/workerman/workerman/Worker.php(2417): Workerman\Events\Event->loop()
#10 /data/wwwroot/webman/vendor/workerman/workerman/Worker.php(1542): Workerman\Worker->run()
#11 /data/wwwroot/webman/vendor/workerman/workerman/Worker.php(1372): Workerman\Worker::forkOneWorkerForLinux(Object(Workerman\Worker))
#12 /data/wwwroot/webman/vendor/workerman/workerman/Worker.php(1346): Workerman\Worker::forkWorkersForLinux()
#13 /data/wwwroot/webman/vendor/workerman/workerman/Worker.php(542): Workerman\Worker::forkWorkers()
#14 /data/wwwroot/webman/start.php(138): Workerman\Worker::runAll()
#15 {main}
```

**Comment by dhw-daniel** [comment]
刚又试了下，可以了，感谢大佬
