### ISSUE TITLE
严重：跨域问题，OPTIONS请求不会经过中间件

### ISSUE THREAD

**Issue by keanu-jinu** [walkor/webman#420]
**目前发现的问题有**：
1. OPTIONS请求不会经过中间件，确定了POST请求会触发中间件
2. 在route.php中配置指定路由的OPTIONS请求可以设置，但是也不会到达中间件
3. [{path:.+}] 有效,但是为什么还是会执行中间件

`Route::options('[{path:.+}]', function () {
    return response('');
});`

**问题**：
1. 如何让任意OPTIONS请求经过中间件 > 目前得到的方案是Route::options('[{path:.+}]', function () {});  这样配置了一个命中所有OPTIONS的路由，然后就可以执行后续流程了，但是如果function里面返回了响应，为什么还会执行中间件

以下是详细情况

**中间件代码**
![image](https://github.com/user-attachments/assets/4c627cbc-56ff-4ea1-a205-b46ed2de7e21)

### 在命令行中请求
`curl -X OPTIONS "http://localhost:8787/test" -I`

**响应中没有配置的header头**
命令行中也没有看到打印的文件路径的日志

>HTTP/1.1 404 Not Found
>Server: workerman
>Content-Type: text/html;charset=utf-8
>Content-Length: 201
>Connection: keep-alive
>

以下方法有效，命令行中也能看到打印的文件路径的日志，为什么已经return response()了，为什么还会执行到中间件
**需要在route.php中配置才有效**
![image](https://github.com/user-attachments/assets/f86429bb-47ce-4ea9-a4a6-b1ccdcf4e976)

响应如下

>HTTP/1.1 204 No Content
>Server: workerman
>Access-Control-Allow-Credentials: true
>Access-Control-Allow-Origin: *
>Access-Control-Allow-Methods: GET, POST, OPTIONS
>Access-Control-Allow-Headers: Content-Type, Authorization, X-Requested-With
>Connection: keep-alive
>Content-Type: text/html;charset=utf-8
>Content-Length: 0

`

**Comment by walkor** [comment]
目前版本404请求不走任何中间件

**Comment by walkor** [comment]
curl -X OPTIONS "http://localhost:8787/api/test" -I
请求的响应是404

**Comment by keanu-jinu** [comment]
> 目前版本404请求不走任何中间件

感谢解答。 那有没有办法配置默认路由呢？没有命中的都走默认路由，现在正则[{path:.*}]会导致报错，因为有些路由已经定义了，是不是只能改404文件或者使用fallback对吧

**Comment by walkor** [comment]
默认就是没命中route.php中的文件时走默认路由，默认路由也找不到文件时返回404

**Comment by keanu-jinu** [comment]
> 默认就是没命中route.php中的文件时走默认路由，默认路由也找不到文件时返回404

OK 感谢，提交了中间件文档的PR，麻烦审批一下

**Comment by walkor** [comment]
这个pr没什么意思，请求不存在的地址没必要进入中间件

**Comment by keanu-jinu** [comment]
> 这个pr没什么意义，请求不存在的地址没必要进入中间件

那如果要实现：所有options请求，都统一设置响应头，应该怎么做呢？
因为我发现route.php中return response('')还是会执行中间件，并没有结束请求。

**Comment by walkor** [comment]
感觉你对中间件机制没理解。
请求的地址是存在的，那么就走中间件，不存在不走。
你在route.php中return response('') 不影响中间件的执行。

给所有options请求设置响应头，这个在你AccessControll中间件已经支持这个功能了，不需要再额外设置什么了。

**Comment by keanu-jinu** [comment]
> 感觉你对中间件机制没理解。 请求的地址是存在的，那么就走中间件，不存在不走。 你在route.php中return response('') 不影响中间件的执行。
> 
> 给所有options请求设置响应头，这个在你AccessControll中间件已经支持这个功能了，不需要再额外设置什么了。

如你所说PR的提案没有意义的话。

比如我有一个路由是/common/info， POST和options请求，如果我要设置CORS是不是需要在route.php中设置
Route.options('/common/info',function(){});
Route.POST('/common/info',['app/controller/CommonController@info']);

如果有很多个路由，每个路由都要类似的写法是吗？感觉会写很多，能提供更优雅的方案吗，感谢

**Comment by walkor** [comment]
不用在route.php设置路由，
webman自带默认路由，/common/info会自动请求CommonController的info方法。
所以route.php里什么都不用写。

只要你在config/middleware.php 里设置了
```php
return [
    '' => [
        app\middleware\AccessControll::class
    ]
];
```
就行了

**Comment by keanu-jinu** [comment]
> 不用在route.php设置路由， webman自带默认路由，/common/info会自动请求CommonController的info方法。 所以route.php里什么都不用写。
> 
> 只要你在config/middleware.php 里设置了
> 
> ```
> return [
>     '' => [
>         app\middleware\AccessControll::class
>     ]
> ];
> ```
> 
> 就行了

不想暴露太多的接口，比如临时禁用的话，就不需要改代码，只需要注释路由定义就好了，我使用了`Route::disableDefaultRoute();`

这种情况，其实我想很多人也会遇到，应该怎么处理呢，使用了`Route::disableDefaultRoute();`的情况

**Comment by keanu-jinu** [comment]
明白了，感谢解答。给大佬敬茶。

walkor ***@***.***> 于 2024年11月12日周二 15:30写道：

**Comment by walkor** [comment]
不客气
