### ISSUE TITLE
1.6版本 cli运行脚本时候

### ISSUE THREAD

**Issue by sy235327** [walkor/webman#422]
按照官网写得脚本再1. 6版本上遇到
<?php
require_once __DIR__ . '/../vendor/autoload.php';
require_once __DIR__ . '/../support/bootstrap.php';

/**
 * test/import data
 * 自定义脚本处理
 */
function main(){
    $request = request();
    if (!$request){
        return "error request";
    }
    echo "test";
}
main();

执行结果告知：

<img width="1515" alt="微信图片_20241118233740" src="https://github.com/user-attachments/assets/4e19e87f-a76f-4be7-9e85-2e60616fb22b">

**Comment by sy235327** [comment]
![1731944235886](https://github.com/user-attachments/assets/a36bea8c-f0ea-464f-a9c9-ab3d8dca45e8)
![image](https://github.com/user-attachments/assets/7943dad8-b4f2-4efd-bd0e-1af2b02c4023)

**Comment by walkor** [comment]
```
composer require workerman/webman-framework ^v1.6.3
```
升级下
