### ISSUE TITLE
当php版本为8.3或8.4时会报错

### ISSUE THREAD

**Issue by wenjian337** [walkor/webman#427]
Fatal error: Declaration of Webman\Http\Request::file(?string $name = null) must be compatible with Workerman\Protocols\Http\Request::file(?string $name = null): mixed in E:\project\webman\vendor\workerman\webman-framework\src\Http\Request.php on line 119
Worker process terminated with ERROR: E_COMPILE_ERROR "Declaration of Webman\Http\Request::file(?string $name = null) must be compatible with Workerman\Protocols\Http\Request::file(?string $name = null): mixed in E:\project\webman\vendor\workerman\webman-framework\src\Http\Request.php on line 119"

**Comment by walkor** [comment]
https://www.workerman.net/q/13501
