### ISSUE TITLE
PHP8.3.8执行报错

### ISSUE THREAD

**Issue by nsnake** [walkor/webman#428]
------------------------------------------ WORKERMAN -------------------------------------------
Workerman version:4.2.1          PHP version:8.3.8           Event-Loop:Workerman\Events\Swoole
------------------------------------------- WORKERS --------------------------------------------
proto   user            worker           listen                 processes    status           
tcp     root            webman           http://0.0.0.0:8787    4             [OK]            
tcp     root            event            none                   1             [OK]            
tcp     root            dailyservices    none                   1             [OK]            
------------------------------------------------------------------------------------------------
Press Ctrl+C to stop. Start success.
PHP Fatal error:  Declaration of Webman\Http\Request::file($name = null) must be compatible with Workerman\Protocols\Http\Request::file(?string $name = null): mixed in /mnt/hgfs/test/php/vendor/workerman/webman-framework/src/Http/Request.php on line 119

Fatal error: Declaration of Webman\Http\Request::file($name = null) must be compatible with Workerman\Protocols\Http\Request::file(?string $name = null): mixed in /mnt/hgfs/test/php/vendor/workerman/webman-framework/src/Http/Request.php on line 119
Worker[33294] process terminated with ERROR: E_COMPILE_ERROR "Declaration of Webman\Http\Request::file($name = null) must be compatible with Workerman\Protocols\Http\Request::file(?string $name = null): mixed in /mnt/hgfs/test/php/vendor/workerman/webman-framework/src/Http/Request.php on line 119"
PHP Fatal error:  Declaration of Webman\Http\Request::file($name = null) must be compatible with Workerman\Protocols\Http\Request::file(?string $name = null): mixed in /mnt/hgfs/test/php/vendor/workerman/webman-framework/src/Http/Request.php on line 119

**Comment by walkor** [comment]
你使用了composer镜像，镜像里包版本是旧的，删除镜像重新升级
composer global config --unset repos.packagist
composer require workerman/webman-framework ^1.6.6 -W
