### ISSUE TITLE
间歇性404，间歇性NotFoundException，间歇性文件引入失败

### ISSUE THREAD

**Issue by bigtran** [walkor/webman#46]
在本地 WSL上调试的时候，使用 http://127.0.0.1:8787/ 访问，无论如何刷新页面都不会出现bug。

放到远程上去之后，用nginx做了反向代理，然后通过
http://47.105.106.73:8787/ 和 http://bigtran.opmonitor.com/ 这两个来访问，都会间歇性的出现这三个bug

1、首页的第一个bug，这个_siteInfo() 是通过 **config/autoload.php** 引入的

`Error: Call to undefined function _siteInfo() in /root/webman/translog/public/_theme/default/inc/header.php:1
Stack trace:
#0 /root/webman/translog/public/_theme/default/index.php(4): require()
#1 /root/webman/translog/support/view/TransLogTheme.php(39): include('/root/webman/tr...')
#2 /root/webman/translog/support/helpers.php(169): support\view\TransLogTheme::render()
#3 /root/webman/translog/app/controller/Index.php(14): view()
#4 /root/webman/translog/vendor/workerman/webman-framework/src/App.php(140): app\controller\Index->index()
#5 /root/webman/translog/vendor/workerman/workerman/Connection/TcpConnection.php(660): Webman\App->onMessage()
#6 /root/webman/translog/vendor/workerman/workerman/Events/Select.php(293): Workerman\Connection\TcpConnection->baseRead()
#7 /root/webman/translog/vendor/workerman/workerman/Worker.php(2417): Workerman\Events\Select->loop()
#8 /root/webman/translog/vendor/workerman/workerman/Worker.php(1542): Workerman\Worker->run()
#9 /root/webman/translog/vendor/workerman/workerman/Worker.php(1372): Workerman\Worker::forkOneWorkerForLinux()
#10 /root/webman/translog/vendor/workerman/workerman/Worker.php(1346): Workerman\Worker::forkWorkersForLinux()
#11 /root/webman/translog/vendor/workerman/workerman/Worker.php(542): Workerman\Worker::forkWorkers()
#12 /root/webman/translog/start.php(136): Workerman\Worker::runAll()
#13 {main}`

2、继续刷新首页，还会出现这个 NotFoundException

`Webman\Exception\NotFoundException: Class 'support\exception\Handler' not found in /root/webman/translog/vendor/workerman/webman-framework/src/Container.php:53
Stack trace:
#0 /root/webman/translog/vendor/workerman/webman-framework/src/App.php(186): Webman\Container->make()
#1 /root/webman/translog/vendor/workerman/webman-framework/src/App.php(170): Webman\App::exceptionResponse()
#2 /root/webman/translog/vendor/workerman/workerman/Connection/TcpConnection.php(660): Webman\App->onMessage()
#3 /root/webman/translog/vendor/workerman/workerman/Events/Select.php(293): Workerman\Connection\TcpConnection->baseRead()
#4 /root/webman/translog/vendor/workerman/workerman/Worker.php(2417): Workerman\Events\Select->loop()
#5 /root/webman/translog/vendor/workerman/workerman/Worker.php(1542): Workerman\Worker->run()
#6 /root/webman/translog/vendor/workerman/workerman/Worker.php(1372): Workerman\Worker::forkOneWorkerForLinux()
#7 /root/webman/translog/vendor/workerman/workerman/Worker.php(1346): Workerman\Worker::forkWorkersForLinux()
#8 /root/webman/translog/vendor/workerman/workerman/Worker.php(542): Workerman\Worker::forkWorkers()
#9 /root/webman/translog/start.php(136): Workerman\Worker::runAll()
#10 {main}`

3、打开 这两个页面的时候，偶尔会404，刷新之后又没有了
http://bigtran.opmonitor.com/achieves
http://bigtran.opmonitor.com/article/hello-translog

是环境问题？一样的composer install的vendor文件。

**Comment by bigtran** [comment]
中间的require_once都改为require了

**Comment by bigtran** [comment]
BTW,  我在做一个基于webman的博客程序、文档程序，有一点点类似hugo，jekyll。

**Comment by cokewenya** [comment]
提示已经很明显了

**Comment by walkor** [comment]
可能是启动了2个webman。将webman停止，然后`ps aux`看下是不是还有个webman在运行。

**Comment by bigtran** [comment]
> 可能是启动了2个webman。将webman停止，然后`ps aux`看下是不是还有个webman在运行。

还真是。
```
root@http-s1:~/webman/translog# ps -aux | grep php
root       843  0.0  1.6 375140 16376 ?        Ss   Oct01   0:08 php-fpm: master process (/etc/php/5.6/fpm/php-fpm.conf)
root      3683  0.0  0.7 154820  7416 ?        S    Oct03   0:00 WorkerMan: master process  start_file=/root/webman/translog/start.php
root      8344  0.0  0.7 154820  7384 ?        S    02:22   0:00 WorkerMan: master process  start_file=/root/webman/translog/start.php
www-data 14607  0.0  3.0 456824 30528 ?        S    Oct03   0:12 php-fpm: pool www
www-data 15718  0.0  1.9 382020 19476 ?        S    10:40   0:01 php-fpm: pool www
root     17949  0.0  0.0  14248   880 pts/1    S+   13:18   0:00 grep --color=auto php
www-data 22992  0.0  2.9 456536 30276 ?        S    Oct02   0:25 php-fpm: pool www
```

php start.php stop 只能停一个，kill 另外一个似乎好了。


**按道理这个webman在同一个端口下应该只能启动一个？？**

**Comment by walkor** [comment]
正常情况下同一个webman项目只能启动一次。启动的时候会检查pid文件及对应pid进程是否存在，如果存在则提示已启动，避免重复启。
但是如果pid文件丢失(比如未停止进程就删除了整个项目等原因)，则无法检查导致重复启动。如果项目重复启动，由于之前的进程载入的是旧代码，如果客户端刚好连接到了旧项目进程，则会出现与预期结果不一致的响应。
