### ISSUE TITLE
关于后期版本更新...

### ISSUE THREAD

**Issue by oscar-mx** [walkor/webman#50]
作者您好，可以分享下webman项目后续的版本规划吗？

**Comment by walkor** [comment]
长远目标是做一个简单易用并且具有超高性能的web框架，它可以使用大部分现有的composer项目或者组件，具有很高的扩展性。
除了web，webman也可以使用workerman的全部功能，这让webman不局限于http项目，你可以用它进军其它领域，例如长连接、即时通讯、物联网、爬虫等工具类、游戏、代理、中间件、微服务、其它功能性服务器等等。

以上目标主体工作都已经完成，后期主要是完善webman配套的组件，例如消息队列、微服务等。近期的工作是实现一些消息队列协议，给webman加几款消息队列的客户端组件。

**Comment by oscar-mx** [comment]
感谢分享
