### ISSUE TITLE
路由是否有简易配置，可以识别到api下v1目录的控制器

### ISSUE THREAD

**Issue by dhw-daniel** [walkor/webman#54]
app 目录下新建了api文件夹，通常还会有子级v1、v2、目录这些，这种时候有没有方法只需要简单的配置路由就能访问到相应的控制器

**Comment by walkor** [comment]
两种方案，
方案一：每个控制器加一个路由
```php
...
Route::any('/api/v1/controller/action', 'app\api\v1\controller\controller@action');
...
```

方案二：写一个适配函数路由到指定控制器
```php
Route::any('/api/v1/{controller}/{action}', function($request, $controller, $action){
    $class_name = 'app\\api\\v1\controller\\' . $controller;
    $controller = new $class_name;
    return call_user_func([$controller, $action], $request);
});
```

**Comment by dhw-daniel** [comment]
感谢，我想要的差不多就是方案二

**Comment by dhw-daniel** [comment]
我采用方案二  在相应的控制器中输出 $request->controller  输出值为空，我想得到当前的控制器和方法需要如何做

**Comment by walkor** [comment]
路由里加一句 $request->controller = $class_name;

**Comment by dhw-daniel** [comment]
好的，感谢

**Comment by Maoxp** [comment]
感谢，也解决了我的问题 
![image](https://user-images.githubusercontent.com/37761489/123508145-29d70180-d6a0-11eb-8d7a-1af68f7efb73.png)

**Comment by Maoxp** [comment]
@dhw-daniel @walkor 
方案二可以使用分组的形式
`Route::group('/api/v1', function () {
    Route::group("/{controller}", function () {
        Route::any("/{action}", function (Request $request, $controller, $action) {
            $class_name = 'app\\api\\v1\controller\\' . $controller;
            $controller = new $class_name;
            $request->controller = $class_name;
            return call_user_func([$controller, $action], $request);
        });
    });
});`

**Comment by bubaishaolong** [comment]
Route::group('/api/v2', function () {
    Route::group("/{controller}", function () {
        Route::any("/{action}", function (Request $request, $controller, $action) {
            $class_name = 'app\\api\\controller\\v2\\' . $controller;
            $controller = new $class_name;
            $request->controller = $class_name;
            return call_user_func([$controller, $action], $request);
        });
    });
});

**Comment by pizriw** [comment]
Route::any('/api/v1/{controller}/{action}', function($request, $controller, $action){
    $class_name = 'app\\api\\controller\\v1\\' . ucfirst($controller);
    $controller = new $class_name;
    return call_user_func([$controller, $action], $request);
});

这样写中间件和自定义异常都会失效


 protected static function exceptionResponse(\Throwable $e, $request)
    {
        try {
            $app = $request->app ?: '';
            $exception_config = Config::get('exception');

            $default_exception = $exception_config[''] ?? ExceptionHandler::class;
            $exception_handler_class = $exception_config[$app] ?? $default_exception;

            /** @var ExceptionHandlerInterface $exception_handler */
            $exception_handler = static::$_container->make($exception_handler_class, [
                'logger' => static::$_logger,
                'debug' => Config::get('app.debug')
            ]);
            $exception_handler->report($e);
            $response = $exception_handler->render($request, $e);
            return $response;
        } catch (\Throwable $e) {
            return Config::get('app.debug') ? (string)$e : $e->getMessage();
        }
    }

exceptionResponse里的 $request->app 就为''了，有啥办法使用自定义异常和中间件吗，试过在路由指定app

**Comment by TNT-ma** [comment]
> 两种方案， 方案一：每个控制器加一个路由
> 
> ```
> ...
> Route::any('/api/v1/controller/action', 'app\api\v1\controller\controller@action');
> ...
> ```
> 
> 方案二：写一个适配函数路由到指定控制器
> 
> ```
> Route::any('/api/v1/{controller}/{action}', function($request, $controller, $action){
>     $class_name = 'app\\api\\v1\controller\\' . $controller;
>     $controller = new $class_name;
>     return call_user_func([$controller, $action], $request);
> });
> ```



> Route::group('/api/v1', function () { Route::group("/{controller}", function () { Route::any("/{action}", function (Request $request, $controller, $action) { $class_name = 'app\\api\\v1\controller\\' . $controller; $controller = new $class_name; $request->controller = $class_name; return call_user_func([$controller, $action], $request); }); }); });

方案2 能不能添加一个中间件？

**Comment by god-daniel** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
