### ISSUE TITLE
getenv() env() 获取不到.env配置

### ISSUE THREAD

**Issue by try-to** [walkor/webman#55]
原"vlucas/phpdotenv": "^4.1" 无问题
新拉取版本变为"vlucas/phpdotenv": ">=4.1,<6.0"  getenv() env() 获取不到.env配置

框架的 env() 需要 将Dotenv::createMutable(base_path())->load() 变为 Dotenv::createUnsafeImmutable(base_path())->load()才能获取

**Comment by walkor** [comment]
感谢反馈，已经修复。
