### ISSUE TITLE
[性能问题?]在http协议下,对于大数据的post,框架数据接收表现出比较慢.

### ISSUE THREAD

**Issue by Iamzz-cn** [walkor/webman#57]
我测试了 
post数据是这样
map_id=102&item_id=274&mine_power=3&cur_energy=11409&cur_cache_power=-3&request_time=1603102417234
和post数据是这样
map_id=102&item_id=69&mine_power=18&unlock_fog_new=1&fog_data=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQEBAQEBAQAAAAEAAAEBAQEBAQEBAQEBAQEBAQEBAQICAQAAAQEBAQEAAQEAAAECAgICAgICAgICAgICAgICAgIBAAAAAAAAAAABAgEAAAECAgICAgICAgICAgICAgICAgICAQAAAAAAAAAAAQEAAAECAgICAgICAgICAgICAgICAgICAgEAAAAAAAAAAQEAAAECAgICAgICAgICAgICAgICAgICAgEAAAAAAAAAAQEAAQICAgICAgICAgICAgICAgICAgICAgIBAAAAAQABAgEAAAECAgICAgICAgICAgICAgICAgICAgIBAAAAAQECAgEAAAECAgICAgICAgICAgICAgICAgICAgEAAAAAAAECAgEAAAECAgICAgICAgICAgICAgICAgICAgEAAAAAAAACAgEAAAECAgICAgICAgICAgICAgICAgICAgEAAAAAAAABAgEAAAECAgICAgICAgICAgICAgICAgICAgEAAAAAAAABAgEAAAECAgICAgICAgICAgICAgICAgICAgIBAAAAAAECAQAAAAECAgICAgICAgICAgICAgICAgICAgEBAAAAAQICAgEAAAECAgICAgICAgICAgICAgICAgICAQAAAAAAAQICAgEAAAECAgICAgICAgICAgICAgICAgIBAAAAAAAAAAECAgEAAAECAgICAgICAgICAgICAgICAgICAQAAAAAAAAECAgIBAAECAgICAgICAgICAgICAgICAgICAgEBAAAAAAECAgEAAAECAgICAgICAgICAgICAgICAgICAgEAAAAAAAECAgEAAAECAgICAgICAgICAQICAQEBAgEBAQEAAAAAAQICAgEAAAECAgICAgICAgIBAAEBAAAAAQAAAAAAAAAAAQICAgEAAAECAgICAgICAgEAAAAAAAAAAAAAAAAAAAAAAQICAgEAAAECAgICAgICAgEAAAAAAAAAAAAAAAAAAAAAAQICAgEAAAECAgICAgICAgEAAAAAAAAAAAAAAAAAAAAAAQICAgEAAAECAgICAgICAgIBAAAAAAAAAAAAAAAAAAAAAAECAgEAAAECAgICAgICAgICAQAAAAAAAAAAAAEAAAAAAAECAgEAAAECAgICAgICAgICAgEAAAAAAAAAAAEBAAAAAQICAgEAAAECAgICAgICAgICAgIBAQAAAAAAAQICAQEBAgICAQEAAAECAgICAgICAgEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAAEBAQEBAQEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA&cur_energy=11577&cur_cache_power=-18&request_time=1603102346563
的时候,处理时间会有明显的差别,后面的至少会比前面的慢4倍左右.

**Comment by Iamzz-cn** [comment]
不知道request对象的处理上是否能优化一下?

**Comment by Iamzz-cn** [comment]
同等数据量的情况下,时间消耗差异不是很明显.

**Comment by Iamzz-cn** [comment]
之前使用 fpm+nginx的时候 这个问题不是很明显, 不知道是不是因为现在http的协议完全使用php实现导致的

**Comment by walkor** [comment]
workerman 解析post数据使用的是php自带的parse_str函数，通过下面脚本压测
```php
<?php
$t = microtime(true);
$i = $j = 1000000;

$post1 = 'map_id=102&item_id=274&mine_power=3&cur_energy=11409&cur_cache_power=-3&request_time=1603102417234';
$post2 = 'map_id=102&item_id=69&mine_power=18&unlock_fog_new=1&fog_data=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQEBAQEBAQAAAAEAAAEBAQEBAQEBAQEBAQEBAQEBAQICAQAAAQEBAQEAAQEAAAECAgICAgICAgICAgICAgICAgIBAAAAAAAAAAABAgEAAAECAgICAgICAgICAgICAgICAgICAQAAAAAAAAAAAQEAAAECAgICAgICAgICAgICAgICAgICAgEAAAAAAAAAAQEAAAECAgICAgICAgICAgICAgICAgICAgEAAAAAAAAAAQEAAQICAgICAgICAgICAgICAgICAgICAgIBAAAAAQABAgEAAAECAgICAgICAgICAgICAgICAgICAgIBAAAAAQECAgEAAAECAgICAgICAgICAgICAgICAgICAgEAAAAAAAECAgEAAAECAgICAgICAgICAgICAgICAgICAgEAAAAAAAACAgEAAAECAgICAgICAgICAgICAgICAgICAgEAAAAAAAABAgEAAAECAgICAgICAgICAgICAgICAgICAgEAAAAAAAABAgEAAAECAgICAgICAgICAgICAgICAgICAgIBAAAAAAECAQAAAAECAgICAgICAgICAgICAgICAgICAgEBAAAAAQICAgEAAAECAgICAgICAgICAgICAgICAgICAQAAAAAAAQICAgEAAAECAgICAgICAgICAgICAgICAgIBAAAAAAAAAAECAgEAAAECAgICAgICAgICAgICAgICAgICAQAAAAAAAAECAgIBAAECAgICAgICAgICAgICAgICAgICAgEBAAAAAAECAgEAAAECAgICAgICAgICAgICAgICAgICAgEAAAAAAAECAgEAAAECAgICAgICAgICAQICAQEBAgEBAQEAAAAAAQICAgEAAAECAgICAgICAgIBAAEBAAAAAQAAAAAAAAAAAQICAgEAAAECAgICAgICAgEAAAAAAAAAAAAAAAAAAAAAAQICAgEAAAECAgICAgICAgEAAAAAAAAAAAAAAAAAAAAAAQICAgEAAAECAgICAgICAgEAAAAAAAAAAAAAAAAAAAAAAQICAgEAAAECAgICAgICAgIBAAAAAAAAAAAAAAAAAAAAAAECAgEAAAECAgICAgICAgICAQAAAAAAAAAAAAEAAAAAAAECAgEAAAECAgICAgICAgICAgEAAAAAAAAAAAEBAAAAAQICAgEAAAECAgICAgICAgICAgIBAQAAAAAAAQICAQEBAgICAQEAAAECAgICAgICAgEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAAEBAQEBAQEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA&cur_energy=11577&cur_cache_power=-18&request_time=1603102346563';

for($k=0; $k<$i; $k++) {
    parse_str($post1, $post);
}
echo $j/(microtime(true) - $t) , "\n";
```
$post1  每秒处理 791390 次
$post2 每秒处理 189878次
性能确实差4倍左右。

由于用的是php自带的parse_str函数，基本上没有优化的空间，如果用php代码去解析会更慢。如果你有办法优化，欢迎发pr。

其实nginx+php-fpm解析这样的数据也一样慢，只不过因为nginx+php-fpm本身就慢，解析post数据再慢一点你不会有很大察觉。
但是workerman由于本身飞快，所以碰到大post数据解析，就会有明显的差距，但是仍然要比nginx+php-fpm快。

**Comment by Iamzz-cn** [comment]
似乎这个问题是没什么好办法解决的了,我已经测试了对于同一个api 在nginx+fpm的情况下表现得更高一些.对于webman,表现出性能不好的大部分时间都是在action之前.是不是我做的优化不够好?

**Comment by walkor** [comment]
以下是我nginx+php-fpm与webman压测对比结果数据，在解析大post数据时，webman性能仍然是nginx+php-fpm的3倍左右。
webman在解析大post数据也没有出现你说的慢了4倍左右，QPS降了大概50%。

**php-fpm代码**
```php
<?php
$post = $_POST;
echo "hello";
```

**webman代码**
```php
<?php
namespace app\controller;
use support\Request;
class Index
{
    public function index(Request $request)
    {
        $post = $request->post();
        return response('hello');
    }
}
```

**结果**
post.txt内容为 
```
map_id=102&item_id=274&mine_power=3&cur_energy=11409&cur_cache_power=-3&request_time=1603102417234
```
**nginx+php-fpm:** Requests per second:    10645.66 [#/sec]
**webman:** Requests per second:    74314.74 [#/sec]

post.txt内容为
```
map_id=102&item_id=69&mine_power=18&unlock_fog_new=1&fog_data=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQEBAQEBAQAAAAEAAAEBAQEBAQEBAQEBAQEBAQEBAQICAQAAAQEBAQEAAQEAAAECAgICAgICAgICAgICAgICAgIBAAAAAAAAAAABAgEAAAECAgICAgICAgICAgICAgICAgICAQAAAAAAAAAAAQEAAAECAgICAgICAgICAgICAgICAgICAgEAAAAAAAAAAQEAAAECAgICAgICAgICAgICAgICAgICAgEAAAAAAAAAAQEAAQICAgICAgICAgICAgICAgICAgICAgIBAAAAAQABAgEAAAECAgICAgICAgICAgICAgICAgICAgIBAAAAAQECAgEAAAECAgICAgICAgICAgICAgICAgICAgEAAAAAAAECAgEAAAECAgICAgICAgICAgICAgICAgICAgEAAAAAAAACAgEAAAECAgICAgICAgICAgICAgICAgICAgEAAAAAAAABAgEAAAECAgICAgICAgICAgICAgICAgICAgEAAAAAAAABAgEAAAECAgICAgICAgICAgICAgICAgICAgIBAAAAAAECAQAAAAECAgICAgICAgICAgICAgICAgICAgEBAAAAAQICAgEAAAECAgICAgICAgICAgICAgICAgICAQAAAAAAAQICAgEAAAECAgICAgICAgICAgICAgICAgIBAAAAAAAAAAECAgEAAAECAgICAgICAgICAgICAgICAgICAQAAAAAAAAECAgIBAAECAgICAgICAgICAgICAgICAgICAgEBAAAAAAECAgEAAAECAgICAgICAgICAgICAgICAgICAgEAAAAAAAECAgEAAAECAgICAgICAgICAQICAQEBAgEBAQEAAAAAAQICAgEAAAECAgICAgICAgIBAAEBAAAAAQAAAAAAAAAAAQICAgEAAAECAgICAgICAgEAAAAAAAAAAAAAAAAAAAAAAQICAgEAAAECAgICAgICAgEAAAAAAAAAAAAAAAAAAAAAAQICAgEAAAECAgICAgICAgEAAAAAAAAAAAAAAAAAAAAAAQICAgEAAAECAgICAgICAgIBAAAAAAAAAAAAAAAAAAAAAAECAgEAAAECAgICAgICAgICAQAAAAAAAAAAAAEAAAAAAAECAgEAAAECAgICAgICAgICAgEAAAAAAAAAAAEBAAAAAQICAgEAAAECAgICAgICAgICAgIBAQAAAAAAAQICAQEBAgICAQEAAAECAgICAgICAgEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAAEBAQEBAQEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA&cur_energy=11577&cur_cache_power=-18&request_time=1603102346563
```
**nginx+php-fpm:** Requests per second:    10095.67 [#/sec]
**webman**: Requests per second:    36050.18 [#/sec]
