### ISSUE TITLE
注意： 当ORM使用 illuminate/database 对应的分页组件必须采用 illuminate/pagination

### ISSUE THREAD

**Issue by dafa168** [walkor/webman#60]

**Comment by dafa168** [comment]
illuminate/database 已经和 illuminate/pagination 耦合在一起了，主要是paginate()分页方法返回的对应渲染分页的组件是  illuminate/pagination ,  webman文档中推荐的分页组件，貌似用不到了。大佬添加到文档中吧 。

**Comment by walkor** [comment]
illuminate/pagination 不影响其它分页组件，其它分页组件仍然可用。
