### ISSUE TITLE
使用内置的curl 是否存在问题？我这边使用curl请求其他网站得不到想要的内容

### ISSUE THREAD

**Issue by dhw-daniel** [walkor/webman#61]
postman 模拟请求，请求地址是正确的，curl模拟请求返回结果为空或者报错

**Comment by walkor** [comment]
webman不会影响curl的默认行为。

你试下把你代码放在一个独立test.php文件中看下能否成功。
test.php
```php
<?php
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
...
```

运行php test.php

**Comment by dhw-daniel** [comment]
感谢，这边的问题，挂了vpn，请求头设置，还有被请求服务器的网关综合下来造成的返回数据不正确，3项全部排除后curl能得到正确的内容，昨天测试都只排除了一项，没有全部排出，一直得不到正确的结果
