### ISSUE TITLE
路由少了一些方法，需要充实下。

### ISSUE THREAD

**Issue by dafa168** [walkor/webman#62]
要不直接用fast-route得了， 感觉里面有很多方法都没封装进来 ？

**Comment by dafa168** [comment]
比如 ： group分组  name名称  route() 函数生成地址 等等

**Comment by dafa168** [comment]
大佬， 还有session部分功能也需要加强下， session配置过期时间， httponly 、csrf  等等 。辛苦。

**Comment by walkor** [comment]
session 过期时间和 httponly在php.ini里设置。
session.cookie_lifetime
session.gc_maxlifetime
session.cookie_httponly

**Comment by dafa168** [comment]
多个项目的情况下就不合适了 。

**Comment by dafa168** [comment]
队列和分布式锁用哪个比较合适点呢？

**Comment by walkor** [comment]
队列刚刚集成了stomp，用于rabbitmq、Apollo、ActiveMQ等队列。
文档：https://www.workerman.net/doc/webman#/queue/stomp

laravel框架的队列和分布式锁可以自己先composer集成下。

**Comment by dafa168** [comment]
好的， 节日快乐！

**Comment by walkor** [comment]
group分组 name名称 route() 函数生成地址 已经支持。
https://www.workerman.net/doc/webman#/route
