### ISSUE TITLE
请教各位Webman和ThinkPHP最大的区别

### ISSUE THREAD

**Issue by amibk** [walkor/webman#78]
请教一下，我看完了webman的整个文档，发现和ThinkPHP有极大的相似度，同时ThinkPHP也是支持常驻进程的。那么请教一下各位大神，有人能说一下webman和ThinkPHP最大的区别在于什么地方？

**Comment by walkor** [comment]
webman 是目标是做世界上性能最高的php web框架，同时具有易用性、高稳定性、高扩展性。
虽然 thinkphp也可以常驻内存(基于workerman或者swoole)，但因为框架要兼容php-fpm workerman swoole三个平台，框架自身会有冗余代码，性能上也会有损耗，所以webman在性能上要高于thinkphp。

性能压测参考：https://www.techempower.com/benchmarks/#section=test&runid=9716e3cd-9e53-433c-b6c5-d2c48c9593c1&hw=ph&test=db&l=zg24n3-1r&a=2 (虽然，thinkphp没有参加，但是仍然可以作为参考)

另外webman支持自定义进程，自定义进程部分其实就是对workerman做了一个简单的包装。也就是除了做web，webman还可以做workerman支持的任何事情，比如tcp、udp、unix socket 、websocket服务，物联网，网络代理，定时任务，消息队列，即时通讯，游戏等等。

webman与其它框架的区别 参见 https://github.com/walkor/webman/issues/18
