### ISSUE TITLE
文件上传

### ISSUE THREAD

**Issue by yzh52521** [walkor/webman#86]
文件上传如果是中文文件名就会报错
上传不了
Notice: Undefined index: key in /webman/vendor/workerman/workerman/Protocols/Http/Request.php on line 546

**Comment by walkor** [comment]
测试了下，没有看到Notice。
发下能重现错误的例子及被上传的文件。

**Comment by yzh52521** [comment]
> 测试了下，没有看到Notice。
> 发下能重现错误的例子及被上传的文件。

 图片名字是中文的就报错  修改成英文或者数字就好使

**Comment by yzh52521** [comment]
> 测试了下，没有看到Notice。
> 发下能重现错误的例子及被上传的文件。

用的就是文档里的示例

**Comment by walkor** [comment]
测试了，没有重现。

**Comment by yzh52521** [comment]
> 测试了，没有重现。

是postman的原因 
谢谢了
