### ISSUE TITLE
域名路由缺少

### ISSUE THREAD

**Issue by amibk** [walkor/webman#87]
是webman还不支持域名路由还是我没有找到，这边想实现一个模块绑定一个子域名，原先用ThinkPHP的时候，可以使用Route::domain进行域名路由配置，在webman好像没有看到，作者是否计划添加此域名路由功能？

**Comment by walkor** [comment]
没看出来域名路由有什么作用。如果想限制域名访问直接用中间键来控制即可。

**Comment by amibk** [comment]
域名路由实际使用场景还是挺常见的，有了域名路由可以将多个子站点一个webman进行解决。
场景举例：
假设现有一个域名test.com
admin.test.com 用来管理后台
api.test.com 生产环境下的开放接口
test-api.test.com 测试环境下的开放接口
android.test.com 安卓专用接口
ios.test.com iOS专用接口
xxx.test.com 电商应用中或开放性博客应用中申请个性子域名使用

等等这些使用场景还是很常见的，域名路由用处还是挺大的呀
