### ISSUE TITLE
无法获取POST请求的数据，但是可以获取GET请求的数据

### ISSUE THREAD

**Issue by amibk** [walkor/webman#89]
使用使用浏览器或Postman进行GET请求时，$request->get();可以正常打印出GET请求的数据。
但是使用Postman进行POST请求时，Content-Type为application/x-www-form-urlencoded，使用$request->post();返回的是空数组，实际是有请求数据的。
同时$request->rawBody();返回的是空文本

**Comment by walkor** [comment]
应该是发的数据不符合http规范。把postman发的原始数据贴出来看下。

**Comment by amibk** [comment]
您好，当时发现无法接收数据后结束了进程，我刚刚在未改变任何代码的情况下启动了webman进程，然后我继续使用Postman进行原样参数请求，此时完全正常。目前无法复现出当时的问题，可以保留一下这个Issues吗？我这边再遇到继续回复在这里

**Comment by 1307super** [comment]
我也遇到了 之前好使没问题, 昨儿前端反应图片上传不了, 使用postman测试时发现,通过form-data发送的数据在后端用input接收为null,用post接收为空数组; 打印rawBody()有文本; 结束进程重新启动,还是无法接收
![image](https://user-images.githubusercontent.com/35326304/114112996-3b660400-9910-11eb-9498-5db2e17a9b2d.png)
![image](https://user-images.githubusercontent.com/35326304/114113014-4882f300-9910-11eb-817f-8e40713fe002.png)

**Comment by 1307super** [comment]
> 我也遇到了 之前好使没问题, 昨儿前端反应图片上传不了, 使用postman测试时发现,通过form-data发送的数据在后端用input接收为null,用post接收为空数组; 打印rawBody()有文本; 结束进程重新启动,还是无法接收
> ![image](https://user-images.githubusercontent.com/35326304/114112996-3b660400-9910-11eb-9498-5db2e17a9b2d.png)
> ![image](https://user-images.githubusercontent.com/35326304/114113014-4882f300-9910-11eb-817f-8e40713fe002.png)

已经解决了, 问题在于浏览器和postman提交form表单截取的boundary_header_buffer里的Content-Disposition是大写, 而判断中用的是小写,导致参数获取不到, 将key转为小写即可
![image](https://user-images.githubusercontent.com/35326304/114115127-d95bcd80-9914-11eb-8546-1d2188231768.png)

**Comment by walkor** [comment]
![image](https://user-images.githubusercontent.com/6073368/114117293-f6929b00-9918-11eb-8a20-85e6abaf29c1.png)

https://github.com/walkor/Workerman/blob/8ad4acc5851e470cbd6ec96e6f804a004eea251b/Protocols/Http/Request.php#L498
源码里这个一直都有转换成小写去判断。

**Comment by 1307super** [comment]
> ![image](https://user-images.githubusercontent.com/6073368/114117293-f6929b00-9918-11eb-8a20-85e6abaf29c1.png)
> 
> https://github.com/walkor/Workerman/blob/8ad4acc5851e470cbd6ec96e6f804a004eea251b/Protocols/Http/Request.php#L498
> 源码里这个一直都有转换成小写去判断。

还真是... 尴尬
