### ISSUE TITLE
多应用 非  Index 控制器  不会自动转向 Controller\index 方法

### ISSUE THREAD

**Issue by imxieke** [walkor/webman#90]
### 多应用 非  `Index` 控制器  不会自动转向 `Controller ` 的 `index` 方法

如     `Index` 控制器` index` 方法会自动访问
但是 `User ` 控制器  `index` 就不会访问 
必须手动指定  `app/user/index` 才可以访问
不知道是哪里没处理好还是不支持 这种方法

**Comment by walkor** [comment]
已经修复，更新 webman-framework到1.0.11 或者后续更高版本，命令为
```
composer require workerman/webman-framework ^1.0.11
```

**Comment by imxieke** [comment]
老哥稳 已经更新 测试没问题 不过我是直接 `composer update` 更新的
