### ISSUE TITLE
框架队列中,redis队列有点问题

### ISSUE THREAD

**Issue by s-3cn** [walkor/webman#91]
不知道为何每次写入redis队列的时候都会多写入一条空内容.
consume时读取到空内容会抛出异常.不过这个不是重点.

**Comment by walkor** [comment]
应该是你传入的数据是空的，自己读下redis看下数据吧

**Comment by s-3cn** [comment]
感谢回复.
生产端是这样.

public function product_downloader( $url )
    {
        $queue = $this->queue_name('downloader');
        $data = [
            'url' => $url,
            'method'=>'get',
            'options'=>[
                CURLOPT_USERAGENT=>'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36',
                CURLOPT_TIMEOUT=>300,
                CURLOPT_FOLLOWLOCATION=>TRUE,
                CURLOPT_MAXREDIRS=>100,
//                 CURLOPT_IPRESOLVE=>CURL_IPRESOLVE_V6,
            ],
            'result'=>[
                'http_code'=>200,
                'content_type'=>'image/',
            ],
        ];
        Log::info("action: product ,url: {$url}");
        return Client::send($queue, $data);
    }
