### ISSUE TITLE
使用视图时,会缓存到以前的内容

### ISSUE THREAD

**Issue by s-3cn** [walkor/webman#92]
两台完全不一样的机器去访问,A机器的访问结果,B机器访问相同页面会小概率获得A机器的结果.而且一直刷新都一样

**Comment by walkor** [comment]
运行 `ps auxf` 看下是不是启动了2个webman

**Comment by s-3cn** [comment]
感谢回复!!
一开始我也以为我启了2个,但是我检查了下确实没有

启动脚本是:

`#! /bin/sh

### BEGIN INIT INFO
# Provides:          webman
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts webman
# Description:       starts the webman daemon
### END INIT INFO

PHPBIN=/usr/bin/php
WEBMAN_SCRIPT=/home/data/web/spider/html/webman/start.php

webman_opts="-d"

case "$1" in
	start)
		echo -n "Starting webman "
		sudo -u centos $PHPBIN $WEBMAN_SCRIPT start $webman_opts
		echo " done"
	;;
	stop)
		echo -n "Gracefully shutting down webman"
		sudo -u centos $PHPBIN $WEBMAN_SCRIPT stop
		echo " done"
	;;

	restart)
		$0 stop
		$0 start
	;;

	reload)
		echo -n "Reload service webman "
		sudo -u centos $PHPBIN $WEBMAN_SCRIPT reload
		echo " done"
	;;

esac
`

**Comment by s-3cn** [comment]
也有可能是restart的时候上一个进程没有关闭直接启动了下一个.我应该修改下restart方式

下次遇到我再检查下是不是启动了两个.

谢谢!
