### ISSUE TITLE
webman会继续更新到什么程度？目前只是修复bug，不再对框架功能做扩充了么？

### ISSUE THREAD

**Issue by xuellbcd** [walkor/webman#96]
很想好好学习一下这个框架。不知道后边会不会增加更多web组件和功能。

**Comment by walkor** [comment]
随着使用者越来越多，更多的需求会被提出来，这些需求会被筛选整理然后加入到框架或者作为组件加入进来。
目前正在准备做 路由域名和路由中间键。

**Comment by xuellbcd** [comment]
> 随着使用者越来越多，更多的需求会被提出来，这些需求会被筛选整理然后加入到框架或者作为组件加入进来。
> 目前正在准备做 路由域名和路由中间键。

我想把控制器的生命周期做的更细一些。比如，想实现每次请求之前都要做的一些事情，或者请求特定的action的时候，做一些事情。每个controller或者action的这种配置如果写到中间件中，感觉不太舒服。
要想实现这样的base controller，我发现传统方式好像不太能行。需要每次在子controller中显式的调用父controller的方法。
所以，我在想，是不是用webman自带的 **DI 模块**来解决？或者还需要一个**service locator**？

**Comment by walkor** [comment]
这种适合放在中间键来做。

传统方式是每个请求都会初始化controller，性能很差也不合理。webman里当controller实例化后就会在内存保留并复用。

**Comment by xuellbcd** [comment]
> 这种适合放在中间键来做。
> 
> 传统方式是每个请求都会初始化controller，性能很差也不合理。webman里当controller实例化后就会在内存保留并复用。

谢谢大佬，俺明白了。

**Comment by walkor** [comment]
webman是常驻内存框架，controller 初始化后会被复用，不会每次请求都初始化一次 。
如果你需要每个请求前或者请求后都做一些事情，可以用中间键来做。

例如：创建文件 `app\middleware\ActionHook.php`(middleware目录不存在请自行创建)

```php
<?php
namespace app\middleware;

use support\bootstrap\Container;
use Webman\MiddlewareInterface;
use Webman\Http\Response;
use Webman\Http\Request;
class ActionHook implements MiddlewareInterface
{
    public function process(Request $request, callable $next) : Response
    {
        $controller = Container::get($request->controller);
        if (method_exists($controller, 'beforeAction')) {
            $before_response = call_user_func([$controller, 'beforeAction'], $request);
            if ($before_response instanceof Response) {
                return $before_response;
            }
        }
        $response = $next($request);
        if (method_exists($controller, 'afterAction')) {
            $after_response = call_user_func([$controller, 'afterAction'], $request, $response);
            if ($after_response instanceof Response) {
                return $after_response;
            }
        }
        return $response;
    }
}
```
在 config/middleware.php 中添加如下配置
```php
return [
    '' => [
	    // .... 这里省略了其它配置 ....
        app\middleware\ActionHook::class
    ]
];
```

这样如果 controller包含了 beforeAction 或者 afterAction方法会自动被调用。
例如：
```php
<?php
namespace app\controller;
use support\Request;
class Index
{
    public function beforeAction(Request $request)
    {
        echo 'beforeAction';
        // 若果想终止执行Action就直接返回Response对象，不想终止则无需return
        // return response('终止执行Action');
    }

    public function afterAction(Request $request, $response)
    {
        echo 'afterAction';
        // 如果想串改结果，可以直接返回Response对象，不想串改则无需return
        // return response('afterAction'); 
    }

    public function index(Request $request)
    {
        return response('index');
    }
}
```

**Comment by xuellbcd** [comment]
> webman是常驻内存框架，controller 初始化后会被复用，不会每次请求都初始化一次 。
> 如果你需要每个请求前或者请求后都做一些事情，可以用中间键来做。
> 
> 例如：创建文件 `app\middleware\ActionHook.php`(middleware目录不存在请自行创建)
> 
> ```
> <?php
> namespace app\middleware;
> 
> use support\bootstrap\Container;
> use Webman\MiddlewareInterface;
> use Webman\Http\Response;
> use Webman\Http\Request;
> class ActionHook implements MiddlewareInterface
> {
>     public function process(Request $request, callable $next) : Response
>     {
>         $controller = Container::get($request->controller);
>         if (method_exists($controller, 'beforeAction')) {
>             $before_response = call_user_func([$controller, 'beforeAction'], $request);
>             if ($before_response instanceof Response) {
>                 return $before_response;
>             }
>         }
>         $response = $next($request);
>         if (method_exists($controller, 'afterAction')) {
>             $after_response = call_user_func([$controller, 'afterAction'], $request, $response);
>             if ($after_response instanceof Response) {
>                 return $after_response;
>             }
>         }
>         return $response;
>     }
> }
> ```
> 
> 在 config/middleware.php 中添加如下配置
> 
> ```
> return [
>     '' => [
> 	    // .... 这里省略了其它配置 ....
>         app\middleware\ActionHook::class
>     ]
> ];
> ```
> 
> 这样如果 controller包含了 beforeAction 或者 afterAction方法会自动被调用。
> 例如：
> 
> ```
> <?php
> namespace app\controller;
> use support\Request;
> class Index
> {
>     public function beforeAction(Request $request)
>     {
>         echo 'beforeAction';
>         // 若果想终止执行Action就直接返回Response对象，不想终止则无需return
>         // return response('终止执行Action');
>     }
> 
>     public function afterAction(Request $request, $response)
>     {
>         echo 'afterAction';
>         // 如果想串改结果，可以直接返回Response对象，不想串改则无需return
>         // return response('afterAction'); 
>     }
> 
>     public function index(Request $request)
>     {
>         return response('index');
>     }
> }
> ```

这个好啊！！原来还可以这么搞，谢谢大佬热心回复。那这样的话，我是不是就可以给controller搞一个基类，然后把权限代码存到基类的beforeAction里边了？

**Comment by walkor** [comment]
可以的

**Comment by dhw-daniel** [comment]
可以将beforeAction  和 afterAction这种方案更新到文档中去么，在这个标题下很容易忽略这个方案

**Comment by walkor** [comment]
已经更新过了，在 https://www.workerman.net/doc/webman#/controller?id=%e6%8e%a7%e5%88%b6%e5%99%a8%e9%92%a9%e5%ad%90-beforeaction-afteraction

**Comment by dhw-daniel** [comment]
我按文档上写的方式创建文件并配置好后启动项目，提示下边信息，我确定我文件创建了，是还有什么地方需要改动么？

```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
middleware app\common\middleware\ActionHook::process not exsits
```

我的config/middleware.php配置如下
```
return [
    '' => [
        // 配置beforeAction afterAction 钩子 https://www.workerman.net/doc/webman#/controller
        app\common\middleware\ActionHook::class,
    ],
];
```
ActionHook文件地址如下
`app\common\middleware`

**Comment by walkor** [comment]
类文件要符合psr4。

**Comment by dhw-daniel** [comment]
我的问题，刚复制没注意后缀变成俩个.php了，我删掉一个后缀重启后提示如下信息

`shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory`

middleware app\common\middleware\ActionHook::process not exsits  这个信息消失了

我的ActionHook.php文件内容如下

```
<?php
/**
 * This file is part of webman.
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the MIT-LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @author    walkor<walkor@workerman.net>
 * @copyright walkor<walkor@workerman.net>
 * @link      http://www.workerman.net/
 * @license   http://www.opensource.org/licenses/mit-license.php MIT License
 */

namespace app\common\middleware;

use support\bootstrap\Container;
use Webman\MiddlewareInterface;
use Webman\Http\Response;
use Webman\Http\Request;

class ActionHook implements MiddlewareInterface
{
    public function process(Request $request, callable $next) : Response
    {
        if ($request->controller) {
            $controller = Container::get($request->controller);
            if (method_exists($controller, 'beforeAction')) {
                $before_response = call_user_func([$controller, 'beforeAction'], $request);
                if ($before_response instanceof Response) {
                    return $before_response;
                }
            }
            $response = $next($request);
            if (method_exists($controller, 'afterAction')) {
                $after_response = call_user_func([$controller, 'afterAction'], $request, $response);
                if ($after_response instanceof Response) {
                    return $after_response;
                }
            }
            return $response;
        }
        return $next($request);
    }
}

```

**Comment by walkor** [comment]
百度下 `shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory`

**Comment by dhw-daniel** [comment]
不好意思，我这边的问题，我本地的环境是将windows下的文件夹共享到linux环境进行交叉开发的，虽然能在linux看到文件目录，但是由于linux实际不存在这个目录，这样就会出现这个问题，部署到真实环境没有这个提示

**Comment by dhw-daniel** [comment]
问下，我在afterAction得到的$response时,我该怎么做，能拿到控制器的结果数据并进行二次处理

**Comment by walkor** [comment]
`$reponse->rawBody()` 获得结果数据

**Comment by dhw-daniel** [comment]
问一下，我这边控制器__construct()  方法中打印输出一个值，第一次请求输出了俩次，这种算是问题么

**Comment by walkor** [comment]
新问题发新的issue吧，不然一致骚扰题主。
把问题描述清楚。贴代码以及配上输出截图。
